### ISSUE TITLE
Add support for "--experimental_allow_proto3_optional" protoc option

### ISSUE THREAD

**Issue by sjoerdvisscher** [rules-proto-grpc/rules_proto_grpc#105]
I'd like to enable [the `--experimental_allow_proto3_optional` protoc option](https://github.com/scalapb/ScalaPB/blob/master/CHANGELOG.md#0110-m3). Maybe this is already possible, but I was not able to figure out how.

**Comment by aaliddell** [comment]
This will be supported in 3.0.0 #106:

```starlark
python_proto_compile(
    name = "person_python_proto",
    protos = ["@rules_proto_grpc//example/proto:person_proto"],
    extra_protoc_args = ["--experimental_allow_proto3_optional"]
)
```

**Comment by sjoerdvisscher** [comment]
Perfect, thanks!
