### ISSUE TITLE
Rules_scala removal of proto deps broke scala_proto_* rules

### ISSUE THREAD

**Issue by Dao007forever** [rules-proto-grpc/rules_proto_grpc#108]
https://github.com/bazelbuild/rules_scala/commit/e9dfbe39fa44a8dc7ab0b9aef46488f215646d9c#diff-880cb55f92402ecc802bce095bcb3e5664f04bc34031e8d33dde1f0b6f239c6f

**Comment by aaliddell** [comment]
Ok, thanks, I'll add this to the 3.0.0 TODO list
