### ISSUE TITLE
`js_grpc_node_library` not providing mandatory DeclarationInfo provider

### ISSUE THREAD

**Issue by pshields** [rules-proto-grpc/rules_proto_grpc#113]
This is a follow-up to some discussion that took place in #103. 

I'm trying out the `js_grpc_node_library` rule from `rules_proto_grpc` 3.0, and while I do see that the target produces the `.d.ts` files as expected, when I try to add the target as a dep to a `ts_project`, I get an error that the target ```does not have mandatory providers: 'DeclarationInfo' or '_ValidOptionsInfo'.``` I would expect `js_grpc_node_library`-based targets to be usable as deps within e.g. a `ts_project`-based target, so I think this may be a bug.

## Example repro

I created https://github.com/pshields/rules_proto_grpc-missing-declaration-info-example as a relatively minimal repro of this issue. You can clone the repo and run `bazel build //:server_ts` to reproduce the issue.

If there's anything you'd like me to do to help investigate or troubleshoot this issue, please let me know. I'd be willing to try digging a little deeper if given some guidance (these kinds of Bazel issues are a little out of my depth.)

/cc @alexeagle

**Comment by slapierre** [comment]
I'm facing the same issue as @pshields with `js_grpc_node_library` when trying to add the target as a dependency in a `ts_library`:

```sh
<merged target REDACTED> doesn't contain declared provider 'DeclarationInfo'
```

The project is similar to the example repo provided in the issue with the small difference that we have `build_bazel_rules_nodejs` version `3.1.0` configured with the backward-compatible switches to use `ts_library` instead of a `ts_project`.

**Comment by aaliddell** [comment]
So if I use that example repo with the test `js-decl-info` branch instead, the `DeclarationInfo` issue is resolved:

```starlark
http_archive(
    name = "rules_proto_grpc",
    urls = ["https://github.com/rules-proto-grpc/rules_proto_grpc/archive/31d5a99f3a31579e2fc9b92adab9d8d0f9f19830.tar.gz"],
    sha256 = "444409acf527947c0b27dc62adba570303049884cfc9d924d40e31e78552f9e8",
    strip_prefix = "rules_proto_grpc-31d5a99f3a31579e2fc9b92adab9d8d0f9f19830",
)
```

After that, the `tconfig.json` file needs to be renamed to `tsconfig.json`

Next there's an issue with mixing dependencies:

```All npm dependencies at the path '' must come from a single workspace. Found 'js_modules' and 'npm'```

And it's here that I run into a wall:
- I can remove the `@npm//grpc` dep and remove that error, but it then obviously complains about not finding grpc.
- I can replace `import * as grpc from 'grpc';` with `import * as grpc from '@grpc/grpc-js';` in server.ts, as the `@grpc/grpc-js` dependency should be coming transitively via `js_grpc_node_library`. But it still complains that `@grpc/grpc-js` cannot be found...
- If I add `@js_modules//@grpc/grpc-js` to the `server_ts` deps, I'm then back to getting the error `All npm dependencies at the path '' must come from a single workspace`, which is now doubly confusing since everything appears to be coming from `@js_modules` but is not.

Any ideas for next steps?

**Comment by aaliddell** [comment]
Fork of repo here: https://github.com/aaliddell/rules_proto_grpc-missing-declaration-info-example

**Comment by slapierre** [comment]
@aaliddell 

I gave it a try with the rule from the `js-decl-info` branch (`sha256=444409ac`) -- I only modified the `http_archive` in `WORKSPACE` to download the rule from the branch.

I am getting an error in `ts-protoc-gen` towards the end when building the `js_grpc_node_library` target. Notice how Bazel is not complaining about the same missing file when re-running  a `bazel build`:

```sh
ERROR: /home/simon/.cache/bazel/_bazel_simon/379478dac0931b915b35380d1cd9c132/external/js_modules/ts-protoc-gen/bin/BUILD.bazel:9:14: @js_modules//ts-protoc-gen/bin:protoc-gen-ts: missing input file 'external/js_modules/node_modules/ts-protoc-gen/CHANGELOG.md', owner: '@js_modules//:node_modules/ts-protoc-gen/CHANGELOG.md'
ERROR: /home/simon/.cache/bazel/_bazel_simon/379478dac0931b915b35380d1cd9c132/external/js_modules/ts-protoc-gen/bin/BUILD.bazel:9:14 97 input file(s) do not exist
INFO: Elapsed time: 8.054s, Critical Path: 0.26s
INFO: 1 process: 1 linux-sandbox.
FAILED: Build did NOT complete successfully
```

````sh
ERROR: /home/simon/.cache/bazel/_bazel_simon/379478dac0931b915b35380d1cd9c132/external/js_modules/grpc-tools/bin/BUILD.bazel:15:14: @js_modules//grpc-tools/bin:grpc_tools_node_protoc_plugin: missing input file 'external/js_modules/node_modules/needle/test/helpers.js', owner: '@js_modules//:node_modules/needle/test/helpers.js'
Target REDACTED failed to build
ERROR: /home/simon/.cache/bazel/_bazel_simon/379478dac0931b915b35380d1cd9c132/external/js_modules/grpc-tools/bin/BUILD.bazel:15:14 7 input file(s) do not exist
INFO: Elapsed time: 0.354s, Critical Path: 0.02s
INFO: 0 processes.
FAILED: Build did NOT complete successfully

**Comment by pshields** [comment]
I fixed the `tsconfig.json` filename on my main branch (sorry about that.) I also set up a separate branch (`using-js-decl-branch`) where I have updated the WORKSPACE file to point to the `js-decl-info` branch of `rules_proto_grpc`. What's weird is, on my existing local copy of the repo, on commit `1997a3ee8bed416ca29d01419798ec480b2f6ca5`, `bazel build //:server_ts` fails with `Middleman _middlemen/external_Sjs_Umodules_Sts-protoc-gen_Sbin_Sprotoc-gen-ts.sh-runfiles failed: 97 input file(s) do not exist`. But if I do a clone of the repo into a new directory and checkout of that same commit, `bazel build //:server_ts` results in `Build completed successfully`. And running `bazel clean` or wiping away `node_modules` in either directory doesn't appear to resolve this discrepancy.

I'm pretty confused right now, so I'm planning to take a break for a little while and come back later today with fresh eyes.

I had actually seen the `All npm dependencies at the path '' must come from a single workspace. Found 'js_modules' and 'npm'` error crop up about a week ago when I was trying to get this working (pre the rules_proto_grpc 3.0 release.) I can't remember which version of rules_proto_grpc I was using at the time. I will plan to look into it further later today. @alexeagle might have some ideas, as he is much more familiar with how `rules_nodejs` works. I have mostly been referring to the `rules_nodejs` documentation over the last couple of weeks to learn how to use that project, and I'm not fully sure how to handle the intricacies of having multiple separate `node_modules` workspaces (e.g. one managed by `rules_proto_grpc` and one managed by the Bazel workspace that is consuming `rules_proto_grpc`.)

**Comment by aaliddell** [comment]
I also saw similar `Middleman` weirdness that appeared to go away with a `bazel clean --expunge`. I can recreate it by switching the rules_proto_grpc version in WORKSPACE then running a rebuild, even if the content of the repo is identical.

In such cases, the symlink at `bazel-rules_proto_grpc-missing-declaration-info-example/external/js_modules/node_modules` to `<snip>/.cache/bazel/_bazel_adam/72485155258fb4a1e35811a4bc5edb5c/external/rules_proto_grpc/js/requirements/node_modules` becomes dangling and leads to the above error. Not sure if that's a rules_nodejs issue or an issue with how we're using it.

It seems like there's a dependency that Bazel isn't aware of, such that wiping the rules_proto_grpc repo (such as by changing version) doesn't recreate the node_modules within, but which `@js_modules` is thinking it's pointing into.

**Comment by pshields** [comment]
@aaliddell  Thank you for the mentioning the `--expunge` flag to `bazel clean`. That was what I was missing. I can now verify that I was able to get my example repro's `ts_project` target to build successfully when using the `js-decl-info` version of `rules_proto_grpc`. @slapierre, does running `bazel clean --expunge` and re-building your target resolve the errors you were seeing?

If it does, perhaps the changes from the  `js-decl-info` branch could be merged to the main branch, and then we could follow up separately on 1) the dangling symlink issue that can be dealt with by running `bazel clean --expunge`, and 2) the build error arising from the apparent comingling of deps from two separate npm workspaces (both of those things seem to me to be separate issues from the missing DeclarationInfo provider issue.) What do you think?

I'm running out of steam on this for today, but I'll try to come back in the coming days to continue nudging forward the remaining issues. Bazel + gRPC + generated TypeScript is a dream come true :grin:

**Comment by aaliddell** [comment]
Ok, I'll merge `js-decl-info` for the next release.

The dangling symlink may be related to the [`symlink_node_modules`](https://bazelbuild.github.io/rules_nodejs/Built-ins.html#yarn_install-symlink_node_modules) option to `yarn_install`, which defaults to true. When I get a chance I'll see if setting to false prevents that error. Alternatively, if left at true, setting `managed_directories` appropriately may inform Bazel of the dependency.

There has been another issue opened for the split deps at #114, which we can use to track that one.

**Comment by slapierre** [comment]
Thank you @aaliddell!

@pshields: I am getting the error reported by Adam after expunging the project:

```sh
All npm dependencies need to come from a single workspace. Found 'external/js_modules/node_modules' and 'external/npm/node_modules'.

```

**Comment by pshields** [comment]
I skimmed the commits in #115 related to this and the NPM workspace deps issue, and what I saw looked good to me. Thanks again @aaliddell for all of the help and responsiveness looking into these issues.

**Comment by aaliddell** [comment]
Ok, thanks for the feedback 👍
