### ISSUE TITLE
Python import error loading in multiple protobuf library

### ISSUE THREAD

**Issue by normmcgarry** [rules-proto-grpc/rules_proto_grpc#124]
In one py_library, I have:
```
py_library(
    name = "foo",
    srcs = [
        "foo_service.py",
    ],
    deps = [
        "//protos:foo_py_grpc",
    ],
)
```
Second library:
```
py_library(
    name = "bar",
    srcs = [
        "bar_service.py",
    ],
    deps = [
        "//protos:bar_py_grpc",
    ],
)
```

In `foo_service.py` (works fine)
```
from protos import foo_pb2_grpc
from protos import foo_pb2
```

In `bar_service.py`
```
from protos import bar_pb2_grpc
from protos import bar_pb2
```

Builds fine, but when I run in a py_binary, I receive:
```
Traceback (most recent call last):
  File "/src/.cache/execroot/workspacename/bazel-out/k8-fastbuild/bin/server/main.runfiles/workspacename/server/main.py", line 3, in <module>
    import bar_service
  File "/src/.cache/execroot/workspacename/bazel-out/k8-fastbuild/bin/server/main.runfiles/workspacename/server/bar_service.py", line 7, in <module>
    from protos import bar_pb2
ImportError: cannot import name 'bar_pb2' from 'protos' (/src/.cache/execroot/workspacename/bazel-out/k8-fastbuild/bin/server/main.runfiles/workspacename/protos/foo_py_grpc_pb/protos/__init__.py)
```

Why is `bar_service` trying to look in `workspacename/protos/foo_py_grpc_pb/protos/` when it should be `workspacename/protos/bar_py_grpc_pb/protos/`

The `foo` proto isn't depended on at all by the `bar_service` library.

Any help would be really appreciated!

**Comment by aaliddell** [comment]
If you add `legacy_create_init=False` to the top level `py_binary`, does the issue persist? Since both import paths start with `protos` and there will be `__init__.py` files generated unless that flag is disabled, Python may stop looking for subsequent matches on the python import paths.
