### ISSUE TITLE
Explicitly load rules_proto, rules_python, rules_cc etc

### ISSUE THREAD

**Issue by aaliddell** [rules-proto-grpc/rules_proto_grpc#13]
In the upcoming Bazel 1.0 release, a number of presently native rules will need to be explicitly loaded. Once 0.29 is released, testing with the incompatible flags can begin:

`py_*` -> https://github.com/bazelbuild/rules_python (https://github.com/bazelbuild/bazel/issues/8893)
`cc_*` -> https://github.com/bazelbuild/rules_cc (https://github.com/bazelbuild/bazel/issues/7643)
`proto_*` -> https://github.com/bazelbuild/rules_proto (https://github.com/bazelbuild/bazel/issues/8891)
`java_*` -> https://github.com/bazelbuild/rules_java (https://github.com/bazelbuild/bazel/issues/8741)

Release 1.0.0 of rules_proto_grpc will be scheduled to coincide with Bazel 1.0 and incorporate these changes.

Presently blocked on 0.29 release.

**Comment by Yannic** [comment]
While you're at it, please also add load statements for `ProtoInfo` and, in the very unlikely case you're using it, `proto_common`. These symbols aren't part of the current incompatible flag because we don't have a whitelisting mechanism for them (yet), but they'll also be removed eventually.

**Comment by aaliddell** [comment]
ProtoInfo is now loaded from rules_proto in #84

**Comment by aaliddell** [comment]
Closing since we moved to `rules_proto` and `rules_python` successfully and the other two are no longer an active proposal in the near future
