### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by hanikesn** [rules-proto-grpc/rules_proto_grpc#131]
With:
```
    http_archive(
        name = "rules_proto_grpc",
        urls = ["https://github.com/rules-proto-grpc/rules_proto_grpc/archive/3.1.1.tar.gz"],
        sha256 = "7954abbb6898830cd10ac9714fbcacf092299fda00ed2baf781172f545120419",
        strip_prefix = "rules_proto_grpc-3.1.1",
    )
```

we see the following debug message on every compile

```
external/io_grpc_grpc_java/java_grpc_library.bzl:82:14: in srcs attribute of @io_grpc_grpc_java//grpclb:load_balancer_java_grpc: Proto source with label @io_grpc_grpc_proto//:grpclb_load_balancer_proto should be in same package as consuming rule
```

I'm wondering whether that's caused by the upstream GRPC-java repo or directly related to rules_proto_grpc.

**Comment by aaliddell** [comment]
I've not seen that one before, but it looks like it may not be directly related to this repo. It looks like it's these lines in grpc-java that are pulling proto srcs from another repo and triggering the warning: 

https://github.com/grpc/grpc-java/blob/c7afb89708057962a2c5249bb7f7992c576e0ae5/grpclb/BUILD.bazel#L24-L28

**Comment by aaliddell** [comment]
Closing this as it looks like it’s an upstream issue
