### ISSUE TITLE
Remove use of proto_library.proto_source_root

### ISSUE THREAD

**Issue by aaliddell** [rules-proto-grpc/rules_proto_grpc#14]
This attribute is destined to be removed in Bazel 1.0: https://github.com/bazelbuild/bazel/issues/7153

The test workspace for this attribute can then also be removed.

**Comment by lberki** [comment]
Note that the functionality of stripping prefixes from proto import paths will still be there, it's just that the attribute was replaced with `strip_import_prefix` / `import_prefix` so that prefixes can also be added and so that it's more coherent with our C++ rules..

**Comment by aaliddell** [comment]
Ah, so does the `proto_source_root` property on the `ProtoInfo` provider remain then?

Those other two new attributes are presently supported and `strip_import_prefix` is tested [here](https://github.com/rules-proto-grpc/rules_proto_grpc/blob/b21cfbb8f5d705b6e9414624958376f0b795b0a4/test_workspaces/strip_import_prefix/BUILD.bazel) (although may need the '/' adding). A test workspace could be added for `import_prefix` though.

**Comment by lberki** [comment]
Yep, the `dep[ProtoInfo].proto_source_root` is going to stay, it's just `proto_library.proto_source_root` that's going away.

**Comment by aaliddell** [comment]
Ok, thanks. I've restored the use of the provider property and added a bunch more test workspaces on the branch for various combinations of those attributes. However, whilst doing so I came across an issue with duplicate files appearing in `ProtoInfo.direct_sources` when using import_prefix: https://github.com/bazelbuild/bazel/issues/9127

**Comment by lberki** [comment]
Commented on the bug. TL;DR: that will be fixed in Bazel 1.0 as an excellent example of acausal development (We fix bugs even before you report them!)

In the meantime, can you live with the duplication?

**Comment by aaliddell** [comment]
Serendipity! It's fine as-is, I've put in a check to skip duplicates in that list.
