### ISSUE TITLE
Add Rust Tonic and Prost support

### ISSUE THREAD

**Issue by aaliddell** [rules-proto-grpc/rules_proto_grpc#143]
Either as additional rules or to replace the current rules as breaking change. These are better supported than the current grpcio etc crates and avoid the flakeyness of the current grpc-sys workarounds.

To do this requires that they have protoc plugins, which neither currently have since they share the same builder core. Currently blocked on:
- https://github.com/tokio-rs/prost/issues/330 / https://github.com/tokio-rs/prost/issues/463 / https://github.com/tokio-rs/prost/pull/492
- https://github.com/hyperium/tonic/issues/750

**Comment by titanous** [comment]
I'm interested in implementing this. I think it would make sense to remove the existing rules and replace them with new rules (that have `tonic` and `prost` in the rule names in case other libraries become popular in the future).

**Comment by aaliddell** [comment]
Do the upstream libraries actually have working protoc plugins yet? There seem to be some external ones, but are these official?

**Comment by titanous** [comment]
They aren't official but they seem to work fine.

**Comment by UebelAndre** [comment]
https://github.com/bazelbuild/rules_rust/issues/915#issuecomment-1079742714 may be useful here.

**Comment by titanous** [comment]
I've made good progress implementing this, but I've run into an issue where the tonic (gRPC) plugin wants to write to the output files from the prost plugin, and I can't see an existing way to make this happen in `compile.bzl`. Suggestions?

**Comment by titanous** [comment]
I've implemented this in #202.

**Comment by aaliddell** [comment]
Closed by #265
