### ISSUE TITLE
@grpc/grpc-js instead of native grpc

### ISSUE THREAD

**Issue by xnerhu** [rules-proto-grpc/rules_proto_grpc#144]
[Native GRPC](https://www.npmjs.com/package/grpc) package for Node.js is deprecated and doesn't support newer Node.js versions. Instead `@grpc/grpc-js` should be used. 

`js_grpc_node_library` rule generates a Typescript definition file `_pb.d.ts`, which imports full `grpc`. 

```ts
// GENERATED CODE -- DO NOT EDIT!

// package: users
// file: user.proto

import * as user_pb from "./user_pb";
import * as grpc from "grpc";
```

Is there a way to use `grpc-js` ?

**Comment by aaliddell** [comment]
There's a PR that's just been merged to dev to support this: https://github.com/rules-proto-grpc/rules_proto_grpc/pull/134

It'll land in master when 4.0.0 is complete. In the meantime, you may be able to pass an option to set the same mode manually.

**Comment by xnerhu** [comment]
May I ask how can I do that? I have this, but it fails. I don't know what the name should be.

```starlark
js_grpc_node_library(
    name = "components_proto",
    options = {
        "grpc_node_ts_plugin": ["mode=grpc-js"],
    },
    protos = [":proto"],
)
```

**Comment by xnerhu** [comment]
Ok I got it. It should be `//js:grpc_node_ts_plugin`.
