### ISSUE TITLE
Add missing dependency to go_validate_library

### ISSUE THREAD

**Issue by ashwin153** [rules-proto-grpc/rules_proto_grpc#149]
### Issue Description

Currently, `go_validate_library` is missing a dependency on `@com_github_envoyproxy_protoc-gen-validate//validate:go_default_library`.

### rules_proto_grpc Version

4.0.0

### Bazel Version

4.1.0

### OS

Ubuntu 20.04

**Comment by aaliddell** [comment]
Thanks. Weird that it successfully compiles without this. FYI the validator rules are possibly still in flux: #146
