### ISSUE TITLE
How to specify the proto include path ?

### ISSUE THREAD

**Issue by pcpLiu** [rules-proto-grpc/rules_proto_grpc#166]
### Description

Hi,

I'm trying to compile a set of rules which use `google/protobuf/timestamp.proto` whoe is installed in my system path `/use/include`

I'm wondering how i can tell the rule to look for it in this location? Thanks!

**Comment by aaliddell** [comment]
You shouldn't depend on .proto files outside of your workspace, but instead use the copies of those files that come from `com_google_protobuf`:

https://github.com/rules-proto-grpc/rules_proto_grpc/blob/caa83f1d78b1b7ac3b891887771c0de7330503a1/example/proto/BUILD.bazel#L17-L24

In your case, you'd depend on `@com_google_protobuf//:timestamp_proto`

**Comment by pcpLiu** [comment]
Thanks!
