### ISSUE TITLE
Cannot build multiple python proto targets along the same directory path

### ISSUE THREAD

**Issue by laurit17** [rules-proto-grpc/rules_proto_grpc#17]
Hi, I'm a current user of these rules (thanks so much for your hard work on them!) in a repo supporting a larger organization. However, I have run into a fairly significant issue: If I have multiple python_proto_library targets for proto libraries in the same directory, I cannot seem to simultaneously depend on more than one of these targets.

I have attached a minimal example that illustrates this - 
https://github.com/laurit17/rules_proto_grpc_failing_example

It seems that the issue is that the output directories of each of these targets is appended to the PYTHONPATH by Bazel, and thus, only one of them can be resolved to the package containing the various targets. The only workaround I can think of is to build all of them in the same target.

As a bit of a newbie to Bazel it is interesting to me to look at the outputs of these rules. For example, in my attached example, if I run `bazel build //proto:b_py_proto`, the outputs are listed as 

`bazel-bin/proto/b_py_proto_pb/proto/b_py2.py`
`bazel-bin/proto/b_py_proto_pb/proto/a_py2.py` (the underling `b_proto` library depends on `a_proto`.

I assume that having the generated `b_py_proto_pb` folder avoids race conditions between rules that have the same generated files (for example, building `:a_py_proto` would also output a file named `a_pb2.py`). However, it comes at the expense of allowing targets to depend on multiple of these Python proto/grpc libraries at once.

I have included some native `cc_proto_library` targets for comparison because interestingly, they do not follow the pattern of the `python_proto_library` rules here. For example, building the `b_cc_proto` target above does generate an `a.pb.h` file as it would have to (just as `a_cc_proto` would) because the underlying `proto_library` depends on `a.proto`, but it does not list it as an output. Is this a potential workaround for the issue above?

Let me know your thoughts. This is an important blocker for us, I am happy to attempt to contribute if necessary!

**Comment by aaliddell** [comment]
Adding `legacy_create_init = False` to the `//example:example` `py_binary` appears to fix this. This flag disables a frustrating default mode in py_binary that creates empty `__init__.py` files in every directory in the runfiles. Due to the way modules are found in python, you can re-use the same module name in multiple folders only if the folders do not contain `__init__.py`. I disable this mode on all py_binary targets, as it doesn't appear to achieve anything useful and should really have its default flipped.

**Comment by laurit17** [comment]
Thank you! Everything works now.

**Comment by smamessier** [comment]
@aaliddell Does this mean I need to write my own `__init__.py` files? If yes, I think we could reopen this as this sounds like a significant limitation. 
Also I have another question: Why are the generated `_pb.py` files not merged in the same tree under `.runfiles`, they seem to recreate a similar hieararchy in a `*_pb` folder.
Thanks for your help!
