### ISSUE TITLE
What is the different between the proto rules here vs in `rules_rust`?

### ISSUE THREAD

**Issue by UebelAndre** [rules-proto-grpc/rules_proto_grpc#173]
### Description

I know I should probably just read through the rules but hoping someone might be able to quickly enumerate differences between the rules at [@rules_proto_grpc//rust](https://github.com/rules-proto-grpc/rules_proto_grpc/tree/4.1.1/rust) and [@rules_rust//proto](https://github.com/bazelbuild/rules_rust/tree/d0adb0217f795db413e4ec471d41d297d44bcadc/proto). I'm wondering if the `rules_rust` rules need to be maintained if the same functionality is offered here. Plus, it'd be nice to have one place for proto/grpc functionality users can go to report issues and collaborate.

**Comment by aaliddell** [comment]
Practically, not a huge amount. Functionally, the APIs are slightly different. If you are just writing Rust, I would suggest using rules_rust's rules. If you have more than Rust in your repo, then perhaps you'll benefit from a common API for proto rules here.

I can't remember if rules_rust use a different proto implementation, but really we are all waiting for prost etc to have a nice plugin to use.
