### ISSUE TITLE
Control output path not to include label.package name?

### ISSUE THREAD

**Issue by dnkoutso** [rules-proto-grpc/rules_proto_grpc#176]
### Description

We have our own folder structure that we have protos into which is causing an issue with the generated import paths.

e.g. given the following .proto folder structure:

```
protos/google/protobuf/descriptor.proto
protos/company/common/common.proto (which imports descriptor.proto).
```

When invoking the rules, they append the package as the output folder from here https://github.com/rules-proto-grpc/rules_proto_grpc/blob/master/internal/common.bzl#L352-L353

e.g

```
bazel build protos//company/common:common_proto
```

This causes a failure in the generated #import statements from protoc.

The final output as it is right now is:

```
out/google/protobuf/_rpg_premerge_descriptor_proto_objc_pb
out/google/protobuf/google/protobuf/.h,.m
out/company/common/_rpg_premerge_common_proto_objc_pb
out/company/common/company/common/.h.m
```

However the imports protoc outputs are all relative to the structure we use so it the case above it outputs `#import "../../google/protobuf"` which fails compilation for common proto given the output folder structure the rules_proto_grpc use.

What we want is:

```
out/google/protobuf/_rpg_premerge_descriptor_proto_objc_pb/...
out/google/protobuf/.h,.m # <----- 
out/company/common/_rpg_premerge_common_proto_objc_pb/...
out/company/common/.h.m # <-----
```

Is there a workaround or something we are missing in achieving this?

**Comment by dnkoutso** [comment]
Its possible a workaround is to pass include paths to fix those but I think having only the root include path sufficient here and faster.

**Comment by aaliddell** [comment]
How are you using the generated Obj-C library? If you are using `objc_proto_library`, the target [should have](https://github.com/rules-proto-grpc/rules_proto_grpc/blob/2e8be8e27cc82203794f14dbdcf37189b02ab722/objc/objc_proto_library.bzl#L39) the correct `includes` attr to ensure the generated imports are valid when used from a downstream `objc_library`.

**Comment by dnkoutso** [comment]
@aaliddell we use `objc_proto_compile` and feed that into an `apple_framework` from https://github.com/bazel-ios/rules_ios.

Not sure if its happening because of that or not, I should try to get you a sample scenario perhaps to demonstrate it...
