### ISSUE TITLE
Please update gRPC to 1.43.0 or greater

### ISSUE THREAD

**Issue by rdesgroppes** [rules-proto-grpc/rules_proto_grpc#179]
### Description

Thanks for considering updating gRPC to version 1.43.0 or greater.

A few rationales why:
- [gRPC Core 1.43.0](https://github.com/grpc/grpc/releases/tag/v1.43.0) fixes out-of-order delivery of `XdsClient` watcher notifications,
- [gRPC Java 1.43.0](https://github.com/grpc/grpc-java/releases/tag/v1.43.0) fixes a `NullPointerException` with sensus as well as the way `XdsServer` handles some configurations,
- [gRPC Java 1.43.**1**](https://github.com/grpc/grpc-java/releases/tag/v1.43.1) fixes a `StatusRuntimeException: INTERNAL: Panic! This is a bug!` when calling `ManagedChannel.enterIdle`,
- [Apache Beam 2.36.0](https://github.com/apache/beam/blob/master/CHANGES.md#2360---2022-02-07) depends on gRPC Java 1.43.2, which leads us to manually resolve (strict) dependency conflicts (side note: Apache Beam 2.37.0 will add Java 17 support for Dataflow, so keeping up with is important to us).

**Comment by hankfanchiu** [comment]
Could we upgrade gRPC to [1.44.0](https://github.com/grpc/grpc/releases/tag/v1.44.0)?

grpc/grpc#28406 (not listed in the release notes) is a nice fix for Bazel.

**Comment by aaliddell** [comment]
I’ll be jumping to the latest version of all the dependencies in #178
