### ISSUE TITLE
Support M1 Mac Architecture for grpc-web

### ISSUE THREAD

**Issue by kunal-rp** [rules-proto-grpc/rules_proto_grpc#180]
### Description

Mono-repo built on intel mac is failing for M1 architecture. The build target is a js grpc web library. 

Support for ```darwin_arm64``` will need to be added here : 
```
tool = select({
        "@bazel_tools//src/conditions:darwin_x86_64": "@grpc_web_plugin_darwin//file",
        "@bazel_tools//src/conditions:linux_x86_64": "@grpc_web_plugin_linux//file",
        "@bazel_tools//src/conditions:windows": "@grpc_web_plugin_windows//file",
    }),
```

**Comment by kunal-rp** [comment]
There is no official ```darwin-arm64``` support for ```grpc-web``` plugin yet, but mirror link could be created following steps in this thread ? https://github.com/grpc/grpc-web/issues/1159

**Comment by kunal-rp** [comment]
It seems like there are github actions for `grpc-web` repo to [build arm artifacts](https://github.com/grpc/grpc-web/actions/runs/2490449724)

would this be sufficient ?

**Comment by aaliddell** [comment]
Those builds look like they [aren't yet attached to a published release](https://github.com/grpc/grpc-web/releases). Once v1.4.0 or v1.3.2 is released hopefully they should have the right plugin executables to use here.

**Comment by loeffel-io** [comment]
+1
