### ISSUE TITLE
Trying to use `ts-proto` instead of `ts-protoc-gen` in TS proto generation

### ISSUE THREAD

**Issue by sashamor** [rules-proto-grpc/rules_proto_grpc#186]
### Description

I've created a proto plugin to use `ts-proto`, following this guide - https://rules-proto-grpc.com/en/latest/custom_plugins.html

```starlark
load("@rules_proto_grpc//:defs.bzl", "proto_plugin")
load(":defs.bzl", "js_proto_compile_2")

proto_plugin(
    name = "js_plugin_2",
    extra_protoc_args = [
        "--ts_proto_out=.",
    ],
    outputs = ["{protopath}_pb.d.ts"],
    tool = "@npm//ts-proto/bin:protoc-gen-ts_proto",
    visibility = ["//visibility:public"],
)

js_proto_compile_2(
    name = "foobar",
    protos = [
        "//common/proto/services/error:error_proto",
    ],
    visibility = ["//visibility:public"],
)
```

And the aspect:
```starlark
js_proto_compile_2 = rule(
    implementation = proto_compile_impl,
    attrs = dict(
        proto_compile_attrs,
        _plugins = attr.label_list(
            providers = [ProtoPluginInfo],
            default = [
                Label("//common/node/protogen:js_plugin_2"),
            ],
            doc = "List of protoc plugins to apply",
        ),
    ),
    toolchains = [str(Label("@rules_proto_grpc//protobuf:toolchain_type"))],
)
```

But I get the error:

```starlark
Use --sandbox_debug to see verbose messages from the sandbox
protoc-gen-ts_proto: program not found or is not executable
Please specify a program using absolute path or make sure the program is available in your PATH system variable
--ts_proto_out: protoc-gen-ts_proto: Plugin failed with status code 1.
Target //common/node/protogen:foobar failed to build
```

Any ideas? This is required for us to build our protos with Bazel. `ts-proto` seems to support (basically) a drop-in replacement for `ts-protoc-gen`, but it uses `protobufjs/minimal`, so its preferred for frontend apps.

**Comment by sashamor** [comment]
Ah, found the issue.

Two changes required:
1) `protoc_plugin_name = "ts_proto"`, to ensure the plugin uses the correct names
2) `outputs = ["{protopath}.ts"]` to match the output formats

So the final rule is

```
proto_plugin(
    name = "js_plugin_2",
    outputs = ["{protopath}.ts"],
    protoc_plugin_name = "ts_proto",
    tool = "@npm//ts-proto/bin:protoc-gen-ts_proto",
    visibility = ["//visibility:public"],
)
```

Might be useful for anyone who needs to use `ts-proto` as well. I'll clean up the code and post a full example soon.

**Comment by sashamor** [comment]
A working Bazel plugin for `ts-proto`:

`BUILD.bazel`
```starlark
load("@rules_proto_grpc//:defs.bzl", "proto_plugin")
load(":ts_proto_compile.bzl", "ts_proto_compile")

proto_plugin(
    name = "ts_proto_plugin",
    options = [
        "exportCommonSymbols=false",
    ],
    # ts-proto outputs Typescript files without the _pb suffix.
    outputs = ["{protopath}.ts"],
    # This parameter tells protoc which prefix to apply to all the arguments (ts_proto_out, ts_proto_opt, etc).
    protoc_plugin_name = "ts_proto",
    # This is a path to the ts_proto binary.
    tool = "@npm//ts-proto/bin:protoc-gen-ts_proto",
    visibility = ["//visibility:public"],
)

ts_proto_compile(
    name = "protogen_protos",
    protos = [
        # Add proto targets here.
    ],
    visibility = ["//visibility:public"],
)
```

`ts_proto_compile.bzl`
```starlark
"""
Definition of ts_proto_compile, which builds protos using the ts-proto library.

Based on @rules_proto_grpc/js/js_proto_compile, and the custom plugins template:
https://rules-proto-grpc.com/en/latest/custom_plugins.html
"""

load(
    "@rules_proto_grpc//:defs.bzl",
    "ProtoPluginInfo",
    "proto_compile_attrs",
    "proto_compile_impl",
)

ts_proto_compile = rule(
    implementation = proto_compile_impl,
    attrs = dict(
        proto_compile_attrs,
        _plugins = attr.label_list(
            providers = [ProtoPluginInfo],
            default = [
                # Everything in this template is the same as the example except this line.
                Label("//common/node/protogen:ts_proto_plugin"),
            ],
            doc = "List of protoc plugins to apply",
        ),
    ),
    toolchains = [str(Label("@rules_proto_grpc//protobuf:toolchain_type"))],
)
```

**Comment by marsh73** [comment]
@sashamor thanks for this... i'm trying to get this to work, with the same ts_proto_compile rule and this in my BUILD.bazel ```proto_plugin(
    name = "ts_proto_plugin",
    options = [
        # Customise the options here.
        "forceLong=string",
        "esModuleInterop=true",
        "useOptionals=all",
        "snakeToCamel=false",
        "useDate=string",
        "env=browser",
        "outputServices=generic-definitions,outputServices=default",
        "outputEncodeMethods=false",
        "outputJsonMethods=false",
        "outputServices=false",
        "useAsyncIterable=true",
    ],
    # ts-proto outputs Typescript files without the _pb suffix.
    outputs = ["{protopath}.ts"],
    # This parameter tells protoc which prefix to apply to all the arguments (ts_proto_out, ts_proto_opt, etc).
    protoc_plugin_name = "ts_proto",
    # This is a path to the ts_proto binary.
    tool = "@webui_npm//ts-proto/bin:protoc-gen-ts_proto",
    visibility = ["//visibility:public"],
)

ts_proto_compile(
    name = "protos",
    protos = [
       "src/usertest.proto"
    ],
    visibility = ["//visibility:public"],
)```

I'm running my build and depending on this "protos" to be available and seeing the following error `every rule of type ts_proto_compile implicitly depends upon the target '//common/node/protogen:ts_proto_plugin', but this target could not be found because of: no such package 'common/node/protogen': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.` 

Assuming `Label("//common/node/protogen:ts_proto_plugin")` should be pointing to something specific?

any help would be great
