### ISSUE TITLE
Use rules_python instead of apt-itude

### ISSUE THREAD

**Issue by bnczk** [rules-proto-grpc/rules_proto_grpc#19]
Does it make sense to use the [rules_python pip_import](https://github.com/bazelbuild/rules_python/blob/master/docs/pip.md#pip_import) instead of [rules_pip](https://github.com/apt-itude/rules_pip)? On first sight I can't find a reason why not to use the more popular rules. This way one does not have to load rules_pip just for the grpc rules.

**Comment by aaliddell** [comment]
There were two reasons:
- rules_python has no method for picking which interpreter to use to fetch the wheels, meaning you may end up trying to run a wheel compiled for Python 2 under Python 3. There are a number of open issues about it (e.g. https://github.com/bazelbuild/rules_python/pull/158), but I haven't tracked if any have made it into master. Without that addressed, most systems would default to `python` being Python 2 and the generated code would fail.
- The interface for using pip dependencies is a lot neater and Bazel'ish in rules_pip. rules_python somewhat requires loading a `requirement` function, whilst `rules_pip` maps the package name to a stable repo name.

**Comment by aaliddell** [comment]
To add: if the first was resolved, I could live with the second if it allowed reducing a dependency.

**Comment by aaliddell** [comment]
Release 1.0.0 now uses rules_python only
