### ISSUE TITLE
Feature request: Would you consider adding support for Square Wire runtime/compiler support?

### ISSUE THREAD

**Issue by dnkoutso** [rules-proto-grpc/rules_proto_grpc#196]
### Description

Square's Wire offers an alternative proto compiler and runtime for Java, Kotlin and Swift.

Would you consider accepting an enhancement that provides `wire_` based rules into the project?

The open source project can be found here https://github.com/square/wire

Thank you!

**Comment by dnkoutso** [comment]
The more I inspect the sources the more tightly coupled things are with `protoc` this might not end up being super easy to manage..but will wait to see if there is any feedback on this request.

**Comment by dnkoutso** [comment]
On more research I think its best to include into the Wire project itself rather than built it  into here.

Sorry fro the thrash!

**Comment by aaliddell** [comment]
Hey, yeah these rules generally depend on a language providing a protoc plugin that we can wrap. From what I can tell (from a very brief skim) they implement their own complete protoc replacement rather than plugins.

**Comment by dnkoutso** [comment]
> (from a very brief skim) they implement their own complete protoc replacement rather than plugins.

yeap!
