### ISSUE TITLE
Failed constraint on darwin_arm64/M1 Mac for `@rules_proto_grpc//doc:markdown_plugin`, upgrade `protoc-gen-doc` to 1.5.1

### ISSUE THREAD

**Issue by lopopolo-brex** [rules-proto-grpc/rules_proto_grpc#198]
### Issue Description

`@rules_proto_grpc//doc:markdown_plugin` does not have a `darwin_arm64` constraint arm in the select clause.

`rules_proto_grpc` brings in platform-specific releases for `protoc-gen-doc` 1.5.0:

https://github.com/rules-proto-grpc/rules_proto_grpc/blob/07fa6e07984747db22afeca160b80631afbf63e6/repositories.bzl#L135-L156

Upstream has a new 1.5.1 release which includes darwin_arm64 artifacts: https://github.com/pseudomuto/protoc-gen-doc/releases/tag/v1.5.1.

Can we update the repositories to include 1.5.1 releases + add the darwin_arm64 release?

The new repository would need to be included here:

https://github.com/rules-proto-grpc/rules_proto_grpc/blob/2250918fd20171d9603b0798df8ecaeddd8f521d/doc/repositories.bzl#L11-L15

and here:

https://github.com/rules-proto-grpc/rules_proto_grpc/blob/07fa6e07984747db22afeca160b80631afbf63e6/repositories.bzl#L535-L545

Several `select` expressions would need to be updated in this file:

https://github.com/rules-proto-grpc/rules_proto_grpc/blob/2250918fd20171d9603b0798df8ecaeddd8f521d/doc/BUILD.bazel#L14-L18

### Log Output

```plain text
ERROR: /private/var/tmp/_bazel_smocherla/ea1f4ddaac5cc988a1e98cb04d5b9c1d/external/rules_proto_grpc/doc/BUILD.bazel:60:13: configurable attribute "tool" in @rules_proto_grpc//doc:markdown_plugin doesn't match this configuration. Would a default condition help?

Conditions checked:
 @bazel_tools//src/conditions:darwin_x86_64
 @bazel_tools//src/conditions:linux_x86_64
 @bazel_tools//src/conditions:windows

To see a condition's definition, run: bazel query --output=build <condition label>.

This instance of @rules_proto_grpc//doc:markdown_plugin has configuration identifier cb0eb31. To inspect its configuration, run: bazel config cb0eb31.

For more help, see https://docs.bazel.build/configurable-attributes.html#why-doesnt-my-select-choose-what-i-expect.
```

### rules_proto_grpc Version

4.1.1

### Bazel Version

5.0.0

### OS

macOS 12 on M1 Mac / darwin_arm64

**Comment by aaliddell** [comment]
Closed in #178
