### ISSUE TITLE
Use Grpc.Net instead of Grpc.Core (csharp)

### ISSUE THREAD

**Issue by sergeykonkin** [rules-proto-grpc/rules_proto_grpc#200]
### Description

Grpc.Core is an old package that wraps C library, it's now in maintenance mode and will be deprecated in May 2023 (see https://grpc.io/blog/grpc-csharp-future/)

Consider migrating to Grpc.Net.* package(s) which is new native implementation by Microsoft.

Grpc.Net.* packages are backward compatible with Grpc.Core and it probably be enough to just replace
```
${TOOL} add --path "${OUTPUT_DIR}" --indent --bazelfile "${FILE_NAME}" Grpc "${GRPC_VERSION}"
```
with
```
${TOOL} add --path "${OUTPUT_DIR}" --indent --bazelfile "${FILE_NAME}" Grpc.Net.Common "${GRPC_VERSION}"
```
at https://github.com/rules-proto-grpc/rules_proto_grpc/blob/master/csharp/nuget/regenerate_packages.sh#L50, but I'm not sure, because I'm not fully understand what happens over there :)

**Comment by aaliddell** [comment]
This is adopted in #178
