### ISSUE TITLE
Build failed on m1 Mac clang-14

### ISSUE THREAD

**Issue by devillove084** [rules-proto-grpc/rules_proto_grpc#206]
### Issue Description

Whether it is the master or dev branch, there is a problem when compiling with the clang14 compiler under mac m1

### Log Output

```plain text
ERROR: /private/var/tmp/_bazel_blade/dfa4959f4abd91f13de8b4eecb56f6b1/external/com_google_absl/absl/base/BUILD.bazel:53:11: Linking external/com_google_absl/absl/base/liblog_severity.so failed: (Exit 1): cc_wrapper.sh failed: error executing command external/local_config_cc/cc_wrapper.sh @bazel-out/darwin_arm64-fastbuild/bin/external/com_google_absl/absl/base/liblog_severity.so-2.params

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
clang-14: error: invalid linker name in argument '-fuse-ld=-debugger-tuning=lldb'
INFO: Elapsed time: 0.561s, Critical Path: 0.40s
INFO: 9 processes: 9 internal.
FAILED: Build did NOT complete successfully
```

### rules_proto_grpc Version

dev

### Bazel Version

bazel 5.2.0-homebrew

### OS

MacOS 12.4

**Comment by aaliddell** [comment]
Without a demo repo or sample workspace, I can't realistically debug this. It's possible an update of the dependencies will pickup a new version of absl that fixes this.

**Comment by aaliddell** [comment]
Could you test with the new 4.20 release? This has updated the dependencies that may be causing trouble
