### ISSUE TITLE
Buf rules woefully out of date

### ISSUE THREAD

**Issue by abhillman** [rules-proto-grpc/rules_proto_grpc#208]
### Issue Description

Here, `v0.56.0` is reference for buf -- https://github.com/rules-proto-grpc/rules_proto_grpc/blob/master/repositories.bzl#L78

Latest release is `v1.6.0` https://github.com/bufbuild/buf/releases/

### rules_proto_grpc Version

master latest (2e8be8e27cc82203794f14dbdcf37189b02ab722)

### Bazel Version

latest

### OS

darwin arm64

**Comment by abhillman** [comment]
Rules that appear to be more up to date https://github.com/bufbuild/rules_buf

**Comment by abhillman** [comment]
I wonder if buf should just be dropped from this repo? Since https://github.com/bufbuild/rules_buf is a lot more maintained. Kind of a footgun for devs.

**Comment by sashamor** [comment]
Updated in https://github.com/rules-proto-grpc/rules_proto_grpc/pull/210.
