### ISSUE TITLE
JS rules don't work with latest protobuf (3.21.x) repo

### ISSUE THREAD

**Issue by srabraham** [rules-proto-grpc/rules_proto_grpc#212]
### Description

For some unknown reason, Google removed JavaScript support from the core protocolbuffers repo: https://github.com/protocolbuffers/protobuf/pull/9874

This makes rules_proto_grpc unable to generate JavaScript protos. The correct new way to do things is to bring in https://github.com/protocolbuffers/protobuf-javascript and use it as a plugin to protoc.

The error I get currently with a rules_proto_grpc JS target is: "protoc-gen-js: program not found or is not executable"

Thanks for your work on this, Adam!

@alexeagle FYI

**Comment by srabraham** [comment]
Relevant: https://github.com/protocolbuffers/protobuf-javascript/issues/127#issuecomment-1204202870

**Comment by aaliddell** [comment]
Thanks for the pointers on this, this is adopted in #178

**Comment by srabraham** [comment]
Awesome, thanks!
