### ISSUE TITLE
Testonly attribute is not propagated

### ISSUE THREAD

**Issue by cpederkoff** [rules-proto-grpc/rules_proto_grpc#218]
### Issue Description

I have a BUILD file that looks like
```
proto_library(
    name = "my_proto_lib",
    testonly = True,
    srcs = ["my_proto.proto"],
)
ruby_proto_library(
    name = "my_ruby_proto_lib",
    testonly = True,
    protos = [":my_proto_lib"],
)
```
and I get the following error: 
`ERROR: /project/BUILD:123: in ruby_proto_compile rule //project:my_ruby_proto_lib_rb_proto_pb: non-test target '//project:my_ruby_proto_lib_rb_proto_pb' depends on testonly target '//project:my_ruby_proto_lib_proto' and doesn't have testonly attribute set`

I think the testonly attribute is not being propagated correctly from the ruby_proto_library to the ruby_proto_compile rule.
This is because it is selecting the keys to propagate using `if k in proto_compile_attrs.keys()`, but `testonly` also needs to be included in that check. 

Thank you. 

### rules_proto_grpc Version

4.0.0

### Bazel Version

5.3.0

### OS

ubuntu

### BUILD Content

```Starlark
proto_library(
    name = "my_proto_lib",
    testonly = True,
    srcs = ["my_proto.proto"],
)
ruby_proto_library(
    name = "my_ruby_proto_lib",
    testonly = True,
    protos = [":my_proto_lib"],
)
```

**Comment by aaliddell** [comment]
Besides `testonly` I should probably also be passing along `visibility`, `tags` and a few others too within the library macros. I'll do this in 4.3.0
