### ISSUE TITLE
csharp still generates Grpc.Core? 

### ISSUE THREAD

**Issue by loeffel-io** [rules-proto-grpc/rules_proto_grpc#224]
### Issue Description

Hello, I try to compile my proto grpc defintions to csharp Grpc.Net.Client instead of Grpc.Core with https://github.com/rules-proto-grpc/rules_proto_grpc which should include this since 4.2.0 but  csharp_grpc_compile still generates Grpc.Core

### rules_proto_grpc Version

4.2.0

### Bazel Version

5.3.2

### OS

darwin arm64

**Comment by aaliddell** [comment]
Yes, this is something I have observed as well. The generated `.cs` files continue to reference `Grpc.Core` in the grpc version currently used by release 4.2.0. I have not checked if this has changed in the latest release of the grpc dotnet plugin.

**Comment by aaliddell** [comment]
This appears to be expected behaviour of the upstream plugins, as the examples on `grpc-dotnet` still continue to reference `Grpc.Core` and the `Grpc.Net.Common` package still depends on `Grpc.Core.Api`
