### ISSUE TITLE
Consider quotes around $@ in compile.bzl

### ISSUE THREAD

**Issue by PetteriAimonen** [rules-proto-grpc/rules_proto_grpc#228]
### Description

Currently [internal/compile.bzl](https://github.com/rules-proto-grpc/rules_proto_grpc/blob/master/internal/compile.bzl#L315) has:

    command = ("mkdir -p '{}' && ".format(premerge_root)) + protoc.path + " $@"  # $@ is replaced with args list

It seems to cause issues when the arguments have spaces or special characters in them, as the extra indirection strips one level of escaping.

The normal way to avoid this in bash is to use `"$@"` instead, which automatically quotes all arguments passed from the outer context.
So to get it through the Python parsing, e.g.:

    command = ("mkdir -p '{}' && ".format(premerge_root)) + protoc.path + ' "$@"'  # $@ is replaced with args list

I can pull request this if wanted. But I'm not sure whether it would break builds, as some users may have already added double-escaping to their arguments to get around the issue.

(Related to nanopb/nanopb#810)

**Comment by aaliddell** [comment]
Thanks for the report, I'll try making a test workspace with some challenging file names and then check the fix resolves that

**Comment by aaliddell** [comment]
I've added a test workspace with special chars and indeed it fails: https://buildkite.com/bazel/rules-proto-grpc-rules-proto-grpc/builds/1767#0184ca95-7220-41d9-b230-84a8c7febfee

Your fix works to resolve this: https://buildkite.com/bazel/rules-proto-grpc-rules-proto-grpc/builds/1768#0184ca9e-01ec-4f25-a093-c3b9d3b24355

Thanks

**Comment by PetteriAimonen** [comment]
Thank you also!
