### ISSUE TITLE
Switching from rules_go `go_grpc_library` to `gateway_grpc_library` creates unwanted need to use "go_package" option in .proto files

### ISSUE THREAD

**Issue by cdelguercio** [rules-proto-grpc/rules_proto_grpc#248]
### Description

I recently switched from rules_go `go_grpc_library` to `gateway_grpc_library` to support grpc gateway, and one of the first things I discovered is that `gateway_grpc_library` doesn't seem to discover import paths that have been defined in `go_proto_library` rules the same way that `go_grpc_library` did.

My org decided that we aren't going to maintain option go_package lines in our protos. This wasn't a problem before, but now I get a bunch of errors when I try and compile our project:

```
ERROR: /my/grpc/file/BUILD.bazel:33:21: Compiling protoc outputs for go_plugin plugin on target //my/grpc/file:go_default_library_pb failed: (Exit 1): bash failed: error executing command /bin/bash -c 'mkdir -p '\''bazel-out/k8-fastbuild/bin/my/grpc/file/_rpg_premerge_go_default_library_pb'\'' && bazel-out/k8-opt-exec-2B5CBBC6/bin/external/com_google_protobuf/protoc "$@"' ... (remaining 5 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
protoc-gen-go: unable to determine Go import path for "my/proto/file.proto"

Please specify either:
	• a "go_package" option in the .proto source file, or
	• a "M" argument on the command line.

See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

--go_plugin_out: protoc-gen-go_plugin: Plugin failed with status code 1.
```

### new method that causes error
```
gateway_grpc_library(
    name = "go_default_library",
    importpath = "grpc/import/path",
    protos = [":proto"],
    visibility = ["//visibility:public"],
    deps = [
        "//example/dep:go_proto",
    ],
)
```

### old method that used rules_go's go_proto_library to resolve import paths
```
go_grpc_library(
    name = "go_proto",
    importpath = "grpc/import/path",
    protos = [
        ":proto",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//example/dep:go_proto",
    ],
)
```

Example dependency:
```
go_proto_library(
    name = "go_proto",
    importpath = "example/dep",
    proto = ":proto",
    visibility = ["//visibility:public"],
    deps = [
        "//dep/of/dep:go_default_library",
    ],
)
```

**Comment by aaliddell** [comment]
Did you update anything else at the same time as this? The only difference between those two rules is the presence of the gateway plugin, which is not the one that is complaining here. 

As the error informs you, to use the Go protoc plugin you need to specify either `go_package` or provide the path on the command line, so what surprises me is that this didn't fail previously unless you were on an older release. It's possible older Go plugins were less strict about this
