### ISSUE TITLE
Need toolchains to build the target, what does this mean?

### ISSUE THREAD

**Issue by iblisylvie** [rules-proto-grpc/rules_proto_grpc#26]
I configured the bazel project follow the section  cpp_grpc_library  of https://rules-proto-grpc.github.io/rules_proto_grpc/cpp/
During the bazel build, I met the error message as following.
Analysis of target '//src:librecog.so' failed; build aborted: no matching toolchains found for types @rules_proto_grpc//protobuf:toolchain_type

What does this mean? And how to fix this?

Best Regards
Qian

**Comment by aaliddell** [comment]
Hi,

Have you got the following lines in your WORKSPACE? These are in the main README.

```
load("@rules_proto_grpc//:repositories.bzl", "rules_proto_grpc_toolchains")
rules_proto_grpc_toolchains()
```

**Comment by iblisylvie** [comment]
Thanks a lot, that works.
