### ISSUE TITLE
Bazel complains on  ..._reflection_proto_only does not have mandatory providers: 'proto' 

### ISSUE THREAD

**Issue by iblisylvie** [rules-proto-grpc/rules_proto_grpc#28]
I configured the bazel project follow the section cpp_grpc_library of https://rules-proto-grpc.github.io/rules_proto_grpc/cpp/

My bazel version is 1.0.0

My WORKSPACE file looks like:
'''
load("@rules_proto_grpc//:repositories.bzl", "rules_proto_grpc_toolchains")
rules_proto_grpc_toolchains()

load("@rules_proto_grpc//cpp:repositories.bzl", rules_proto_grpc_cpp_repos="cpp_repos")
rules_proto_grpc_cpp_repos()

load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")
grpc_deps()
'''

My proto build file looks like:
'''
package(default_visibility = ["//visibility:public"])

load("@rules_proto_grpc//cpp:defs.bzl", "cpp_grpc_library")

proto_library(
    name = "protos",
    srcs = [
        "tts.proto",
        "speech.proto",
        "sagittarius_event_server.proto",

    ],
    visibility = [
        "//visibility:public",
    ],
)

cpp_grpc_library(
    name = "grpc_lib",
    deps = [":protos"],
)
'''

During the bazel build, I met the error message as following.
ERROR: /home/qli/.cache/bazel/_bazel_qli/94d4690820716448475d1a244f54f936/external/com_github_grpc_grpc/src/proto/grpc/reflection/v1alpha/BUILD:21:1: in srcs attribute of _generate_cc rule @com_github_grpc_grpc//src/proto/grpc/reflection/v1alpha:_reflection_proto_grpc_codegen: '@com_github_grpc_grpc//src/proto/grpc/reflection/v1alpha:_reflection_proto_only' does not have mandatory providers: 'proto'. Since this rule was created by the macro 'grpc_proto_library', the error might have been caused by the macro implementation in /home/qli/.cache/bazel/_bazel_qli/94d4690820716448475d1a244f54f936/external/com_github_grpc_grpc/src/proto/grpc/reflection/v1alpha/BUILD:21:1

It seems maybe an uncompatible version? Do you know how to fix this?

Best Regards
Qian

**Comment by aaliddell** [comment]
Please see the note on the readme and #22, Bazel 1.0.0 is not fully supported yet

**Comment by iblisylvie** [comment]
ok, I see, I was reading the master README, that's why. 
Now I use tag 0.2.0 readme, so I just to confirm which bazel version do you recommend to compile the code?

**Comment by iblisylvie** [comment]
works with bazel version 0.27.0.
