### ISSUE TITLE
Settings Scala Version to 2.12.8

### ISSUE THREAD

**Issue by amit-traiana** [rules-proto-grpc/rules_proto_grpc#29]
Hi :-)

I'm using `scala_grpc_compile` to build couple of gRPC services. It looks like `scala_grpc_compile` basically use `rules_scala`. `rules_scala` allows you to set the Scala version your compiling against with the `scala_repositories()` like so:

```
scala_repositories((
    "2.12.8",
    {
        "scala_compiler": "f34e9119f45abd41e85b9e121ba19dd9288b3b4af7f7047e86dc70236708d170",
        "scala_library": "321fb55685635c931eba4bc0d7668349da3f2c09aee2de93a70566066ff25c28",
        "scala_reflect": "4d6405395c4599ce04cea08ba082339e3e42135de9aae2923c9f5367e957315a",
    },
))
```

Along with settings the Scala proto repositories:
```
scala_proto_repositories(scala_version = "2.12.8")
```
However, while it works when I try it directly with `rules_scala`, It failed when using `scala_grpc_compile`:

```
Exception in thread "main" java.lang.NoSuchMethodError: scala.Predef$.refArrayOps([Ljava/lang/Object;)Lscala/collection/mutable/ArrayOps;
        at scalapb.compiler.ProtobufGenerator$.parseParameters(ProtobufGenerator.scala:1742)
        at scalapb.compiler.ProtobufGenerator$.handleCodeGeneratorRequest(ProtobufGenerator.scala:1767)
        at CompilerPlugin$.main(CompilerPlugin.scala:13)
        at CompilerPlugin.main(CompilerPlugin.scala)
--grpc_scala_plugin_out: protoc-gen-grpc_scala_plugin: Plugin failed with status code 1.

```

It looks like a versions difference with ScalaPB. So I forked the repository and changed the following in `repositories.bzl`:

```
    "com_github_scalapb_scalapb": {
        "type": "http",
        "urls": ["https://github.com/scalapb/ScalaPB/releases/download/v0.9.0/scalapbc-0.9.0.zip"],
        # "sha256": "bda0b44b50f0a816342a52c34e6a341b1a792f2a6d26f4f060852f8f10f5d854",
        "strip_prefix": "scalapbc-0.9.0/lib",
        "build_file": "@rules_proto_grpc//third_party:BUILD.bazel.com_github_scalapb_scalapb",
    },
```

And set the correct jar:
```
java_import(
    name = "compilerplugin",
    jars = ["com.thesamet.scalapb.compilerplugin-0.9.0.jar"],
    visibility = ["//visibility:public"],
)
```
(By the way. Is there a way to change the version rather than directly fork and change the file?)
Getting a different error now:

```
Exception in thread "main" java.lang.NoSuchMethodError: scala.Predef$.refArrayOps([Ljava/lang/Object;)Lscala/collection/mutable/ArrayOps;
        at scalapb.compiler.ProtobufGenerator$.parseParameters(ProtobufGenerator.scala:1853)
        at scalapb.compiler.ProtobufGenerator$.handleCodeGeneratorRequest(ProtobufGenerator.scala:1882)
        at CompilerPlugin$.main(CompilerPlugin.scala:13)
        at CompilerPlugin.main(CompilerPlugin.scala)
--grpc_scala_plugin_out: protoc-gen-grpc_scala_plugin: Plugin failed with status code 1.
Target //cme/orgmodel/api/v2:orgmodel_scala_better_grpc failed to build
Use --verbose_failures to see the command lines of failed build steps.
```

Looks like a version mismatch again. Am I'm missing here something? Maybe it's the `scala-library` import that is hard-coded to 2.11 (it's taken from the scalapb I'm guess).

Thanks!

**Comment by aaliddell** [comment]
Could you try the changes in the bazel-1.0-support branch, as the Scala rules have had a few updates there?

**Comment by amit-traiana** [comment]
I created a quick example repository to test it (as the repository I'm using is still 0.29.1 as many of the rules I'm using does not support 1.0 yet). No compilation error, looking good!

I'm guessing that support in 1.0 is around the corner and It's probably not worth fixing the master. 

I do have two questions though:

1. Is it possible to influence `repositories.bzl` externally if for example I want to control the `scalapb` version?

2. I noticed that when you build a `java_proto_library` or `scala_proto_library`, dependencies are being added to the JAR. So if my library depends for example one a Google proto, that google proto compiled classes is being added to the JAR. Is that's by design? Because the native `java_proto_library` and the `scala_rules` - `scala_proto_library` doesn't do that - and no matter which dependencies are stated - all the JAR will include is the generated protobuf `src` files. 

And thanks for maintaining the project! `rules_proto` seems a bit slow on updates and fixes, and since we use multiple languages, he had to patch a lot of rules around. I just stumbled into this Project today, and it's looks like it's going to make everything much more easier for us :-)

**Comment by aaliddell** [comment]
> I created a quick example repository to test it (as the repository I'm using is still 0.29.1 as many of the rules I'm using does not support 1.0 yet). No compilation error, looking good!

:+1: That somewhat surprises me. Getting scala to even pass the build was a pain since I don't know the language, so I'm surprised it actually works...

> I'm guessing that support in 1.0 is around the corner and It's probably not worth fixing the master.

Yep, if it works on that branch I'd pin the working commit in your WORKSPACE until it's merged to master. Version 1.0 support is mostly limited by my time available to get things working and trying to piece together languages I don't know.

> 
> I do have two questions though:
> 
>     1. Is it possible to influence `repositories.bzl` externally if for example I want to control the `scalapb` version?

You shoud be able to pass `com_github_scalapb_scalapb_ref` and `com_github_scalapb_scalapb_sha256` to the rule to alter its behaviour, although I've not tested those. Possibly they won't work on a non-github fetch.
 
>     2. I noticed that when you build a `java_proto_library` or `scala_proto_library`, dependencies are being added to the JAR. So if my library depends for example one a Google proto, that google proto compiled classes is being added to the JAR. Is that's by design? Because the native `java_proto_library` and the `scala_rules` - `scala_proto_library` doesn't do that - and no matter which dependencies are stated - all the JAR will include is the generated protobuf `src` files.

That's the behaviour this project has inherited from rules_proto. If you just want a jar, java_proto_compile should just give you the jar that protoc generates that you can then do what you want with.

This is the usual behaviour of `*_proto_{compile|library}` in this repo: the `compile` rule just runs protoc and gives you the outputs, whilst the `library` rule attempts to wrap those outputs for use in a way that meets most 'standard' use cases. If you want to adjust the library, use the `compile` rule and create the library how you desire.

**Comment by amit-traiana** [comment]
> That somewhat surprises me.
Well, the example repository was pretty basic. Tomorrow I'll try to migrate the real project into 1.0. The Scala code there is more complex. But this will take a bit of time probably as I'm guessing other rules will also have problem with 1.0. I'll keep you update once it's done :-)

> You shoud be able to pass com_github_scalapb_scalapb_ref and com_github_scalapb_scalapb_sha256 to the rule to alter its behaviour
You mean when initiating it in the workspace? 

> That's the behaviour this project has inherited from rules_proto. 
Yep. `rules_proto` was indeed acting the same. I'll try create my own jar with `java_library` and `proto_compile` see if it solves the problem. 

Thank you!

**Comment by amit-traiana** [comment]
A quick update. I migrate the whole project into Bazel 1.X and I'm happy to let you know again that everything Scala works as expected. So as far as I concern - you can remove the 'Experimental' from Scala documentation ;-)

I did noticed something you Go you might want to fix (let me know if for the sake of order you prefer me to open a new issue). It seems like `go_rules` can't work without `gazelle`. You probably want to add `gazelle` as Go rule dependency when setting up the [workspace](https://github.com/rules-proto-grpc/rules_proto_grpc/tree/master/go#workspace).

**Comment by aaliddell** [comment]
Excellent!

Gazelle is added in the 1.0 branch, as there are quite a few go related changes: https://github.com/rules-proto-grpc/rules_proto_grpc/tree/bazel-1.0-support/go

**Comment by amit-traiana** [comment]
Oh, I'm sorry. Your right - I have been checking the documentation on the master branch.

There's another thing I noticed today. I tried today to use `scala_grpc_compile` (up until now I only used `scala_proto_compile`). And while it compiles and everything looks fine, inspecting the JAR show it missing the `grpc` classes in it. It looks exactly like the `scala_proto_compile` jar (and it shouldn't).

I think your missing a `toolchain` over there. Based on `scala-rules` [documentation](https://github.com/bazelbuild/rules_scala/blob/1e258720c3adb66002310378128f29eb63f50dd1/docs/scalapb_proto_library.md), if you want to compile GRPC, you have to set up a `toolchain` and set `with_grpc` to be `true`.

When using `rules-scala` directly, it's already been done for you by default on the [BUILD](https://github.com/bazelbuild/rules_scala/blob/1e258720c3adb66002310378128f29eb63f50dd1/scala_proto/BUILD) file. 

So I think that the `with_grpc`  parameter needed to be used everything a user is calling `scala_grpc_*` (but not when calling `scala_proto_*`).

Thanks again!

**Comment by aaliddell** [comment]
Ah oops, I removed the `grpc` option from the ScalaPB plugin when tidying up, so the gRPC rule ends up building the exact same thing as the proto rule. I'll re-add it on the branch shortly, let me know if that fixes it.

**Comment by amit-traiana** [comment]
Haven't test it yet, but now I can see the `gRPC$`files inside the JAR. Thanks yet again!

**Comment by aaliddell** [comment]
Ok, there’s possibly still an issue during runtime that has shown up during testing, so don’t be surprised if that shows up. Something regarding GeneratedMessage

**Comment by amit-traiana** [comment]
I'm out of work today so I won't be able to check it, but I will give it a try tomorrow and let you know if I'm experiencing the same run-time error.

**Comment by amit-traiana** [comment]
I completely forgot about this issue. I can confirm I was able to compile the Scala code, and run-time looks good here. No error. So I'm not sure which runtime error you had problem with, but everything working here and I think we can close this one. 
Thanks!
