### ISSUE TITLE
Upgrade `com_google_protobuf` from v21.10 to v24.4

### ISSUE THREAD

**Issue by teadetime** [rules-proto-grpc/rules_proto_grpc#290]
### Description

The 21.10 tag is over a year old: https://github.com/protocolbuffers/protobuf/tags?after=v3.22.0-rc1 and should be updated to something more recent.

Upgrading this protobuf dependency will allow this to work with https://github.com/pybind/pybind11_protobuf

How hard/large of a change is this?

**Comment by prm-dan** [comment]
Any update on this?

**Comment by aaliddell** [comment]
The 5.0.0 release has protobuf 27.1
