### ISSUE TITLE
When will rules_proto_grpc 1.61.0 be released?

### ISSUE THREAD

**Issue by Ryang20718** [rules-proto-grpc/rules_proto_grpc#304]
### Description

Wondering when this new release will occur? will need this for bazel 7.0.0!

**Comment by aaliddell** [comment]
You need to go follow the issue here, there's nothing that can be done in this repo: https://github.com/grpc/grpc/issues/35271

At present, the version of grpc used is the latest version available in BCR: https://github.com/bazelbuild/bazel-central-registry/tree/main/modules/grpc

**Comment by aaliddell** [comment]
The 5.0.0 release has grpc 1.65.0
