### ISSUE TITLE
Update the docs for Go bzlmod (and gazelle) 

### ISSUE THREAD

**Issue by udf2457** [rules-proto-grpc/rules_proto_grpc#311]
### Description

I have been struggling to get bazel to compile protobuf files for me into Go.

#299 suggests that [unlike certain others](https://github.com/stackb/rules_proto/issues/319), you have bzlmod support, which is good.

However the example project referred to in the docs [https://github.com/rules-proto-grpc/rules_proto_grpc/tree/master/examples/go/go_proto_compile](https://github.com/rules-proto-grpc/rules_proto_grpc/tree/master/examples/go/go_proto_compile) is based around `WORKSPACE` and doesn't use `gazelle` either.

It would be nice if you could update the docs/example to provide a more current (i.e. bzlmod) and real-world (i.e. gazelle) example.

Thank you.

**Comment by aaliddell** [comment]
- For bzlmod support, that example you link already is running under bzlmod. The empty WORKSPACE file is required to mark the workspace boundary even under bzlmod. At present an alpha version is available in BCR: https://registry.bazel.build/modules/rules_proto_grpc_go
- For Gazelle: see #220. Short answer is Gazelle is not supported at present
