### ISSUE TITLE
aarch64 compatibility issue

### ISSUE THREAD

**Issue by nwittstruck** [rules-proto-grpc/rules_proto_grpc#317]
### Issue Description

When using rules_proto_grpc on a `linux_aarch64` system, I'm getting the attached output. It seems `aarch64` is not supported yet? This issue looks similar to https://github.com/rules-proto-grpc/rules_proto_grpc/pull/222/files, however I'm not very familiar with rules_proto_grpc, so I might as well be wrong.

1. I'm using the UTM/Apple Silicon version of the [GitLabs GDK in a box](https://docs.gitlab.com/ee/development/contributing/first_contribution/configure-dev-env-gdk-in-a-box.html). The image is based on debian aarch64. 
2. I'm running [make regenerate-proto](https://gitlab.com/gitlab-org/cluster-integration/gitlab-agent/-/blob/master/Makefile?ref_type=heads#L62), which is basically `bazel run //build:extract_generated_proto`. Same issue when directly calling `bazel run //build:extract_generated_proto`.

I hope this is the right place to ask, as I'm not sure if this is related to `rules_proto_grpc` or because of a compatibility issue of e.g. the markdown plugin. Either way, thanks for the great work!

### Log Output

```plain text
rules_proto_grpc/doc/BUILD.bazel:63:13: configurable attribute "tool" in @rules_proto_grpc//doc:markdown_plugin doesn't match this configuration. Would a default condition help?
Conditions checked:
 @bazel_tools//src/conditions:darwin_arm64
 @bazel_tools//src/conditions:darwin_x86_64
 @bazel_tools//src/conditions:linux_x86_64
 @bazel_tools//src/conditions:windows
To see a condition's definition, run: bazel query --output=build <condition label>.
This instance of @rules_proto_grpc//doc:markdown_plugin has configuration identifier eb3e857. To inspect its configuration, run: bazel config eb3e857.
For more help, see https://bazel.build/docs/configurable-attributes#faq-select-choose-condition.
```

### rules_proto_grpc Version

4.6.0

### Bazel Version

6.5.0

### OS

Linux gdk 6.1.0-13-arm64 SMP Debian 6.1.55-1 (2023-09-29) aarch64 GNU/Linux

### Link to Demo Repo

https://gitlab.com/gitlab-org/cluster-integration/gitlab-agent

**Comment by aaliddell** [comment]
ARM64 support for the doc plugin has been added in 5.0.0
