### ISSUE TITLE
Python path conflict when a binary depends on several python_proto_library

### ISSUE THREAD

**Issue by skeptic-monkey** [rules-proto-grpc/rules_proto_grpc#32]
I have have a python_binary that have dependencies on several python_proto_library.
something as follow:

```
/dir1/my_python_binary  (py_binary)
/dir2/proto/proto_a.proto (python_proto_library)
/dir2/proto/proto_b.proto (python_proto_library)
/dir3/proto/proto_c.proto (python_proto_library)
```

`proto_c` depends on `proto_a`
my_python_binary depends on `proto_b` and `proto_c`

all of this which generates the following directory structure:

```
bazel-bin/dir1/my_python_binary.run_files/proto_a_pb/dir2
bazel-bin/dir1/my_python_binary.run_files/proto_c_pb/dir2
bazel-bin/dir1/my_python_binary.run_files/proto_c_pb/dir3
```
bazel adds `bazel-bin/dir1/my_python_binary.run_files/proto_a_pb` and `bazel-bin/dir1/my_python_binary.run_files/proto_c_pb` to the sys.path

which means that there are 2 different directory matching the following import statement:
`from dir2 import *`

and python will import everything only from the first directory matching in the sys.path hence part of my protos are not reachable.

this issue might be related to this one to : https://github.com/rules-proto-grpc/rules_proto_grpc/issues/25

**Comment by aaliddell** [comment]
Does importing by full name, rather than by `*`, work? e.g.

```
import dir2.proto.proto_a_pb2
```

**Comment by bnczk** [comment]
I think I have reproduced it(https://github.com/bnczk/rpg_py_conflict). The order of the imports in the client matters for me. When the bar_py_proto is imported second, the client does not work and does not find the proto.bar module

**Comment by aaliddell** [comment]
Solution established via Slack was that `legacy_create_init = False` was missing on `py_binary` targets
