### ISSUE TITLE
How to use latest release with HTTP_ARCHIVE in WORKSPACE

### ISSUE THREAD

**Issue by desh-woes** [rules-proto-grpc/rules_proto_grpc#354]
### Description

The samples included uses the Module files to override the rules for building the proto library. 

However, the setup does not work for a plain WORKSPACE + Http archive combination, as it seems to require specifying a build file. 

For context, I have tried 

```
http_archive(
    name = "rules_proto_grpc",
    sha256 = "c6b30f95470792f9894e3b6b6ac271813a7b59f6cb43a09bca15213d309d45f9",
    strip_prefix = "rules_proto_grpc-5.0.0",
    urls = ["https://github.com/rules-proto-grpc/rules_proto_grpc/archive/refs/tags/5.0.0.tar.gz"],
)
```

And that does not work. Does anyone have a pointer for getting this to work using a WORKSPACE? Thank you.

**Comment by desh-woes** [comment]
Thank you for confirming. Can you help confirm the earlier version with support for https://protobuf.dev/editions/overview/#migrating. Thank you.

**Comment by aaliddell** [comment]
You'll have to check with the protobuf repo which 'edition' corresponds to which version number, but the version in the 4.x.x releases is now unlikely to be updated
