### ISSUE TITLE
Plugin output_directory fails when no outputs generated

### ISSUE THREAD

**Issue by aaliddell** [rules-proto-grpc/rules_proto_grpc#39]
See https://github.com/rules-proto-grpc/rules_proto_grpc/issues/31#issuecomment-566053294

If a plugin that uses `output_directory` does not produce any outputs (e.g. gRPC plugin with no services), the copy to merge the directories will fail. Most plugins are well behaved, in that they will generate empty output files even when there are no services, but this should not be a hard requirement.

The command should first check that outputs have been generated or otherwise allow `cp` to fail.

**Comment by amit-traiana** [comment]
Thank you. That indeed solved that problem, but not all the problems with `cp`. I'm seeing the following error:

````
cp: warning: source directory 'bazel-out/k8-fastbuild/bin/external/com_github_scalapb_scalapb_repo/scalapb_proto/gateway_grpc_compile_aspect_verb0/_plugin_grpc_gateway_plugin/.' specified more than once
```

I'm assuming that's because two targets depend on the same `dep` - so the folder is specified twice and `cp` fails due to that.

**Comment by aaliddell** [comment]
I've opened a new issue for this: https://github.com/rules-proto-grpc/rules_proto_grpc/issues/41
