### ISSUE TITLE
Setting up Python 2/3 in Windows Doesn't Work

### ISSUE THREAD

**Issue by amit-traiana** [rules-proto-grpc/rules_proto_grpc#45]
Hi,

It's not something you can fix I think, but I think it's probably worth mentioning it on the documentation.

When installing Python 2 or 3 in Windows, the name of the executable is `python.exe`. When you use Python2 rules, it's looking for `python2` and when Python3 it's looking for `python3`. Even if you can figure out it's Windows run - calling 'Python' is not enough because you don't know which Python is currently installed.

What I did  here is to rename `Python.exe` (which is Python2) to `Python2.exe` and the `Python.exe` (which is in a different folder and this time is Python3) to `Python3.exe`.

Probably worth mentioning in the documentation as a workaround, as I don't see a better option.
Thanks!

**Comment by aaliddell** [comment]
Ok, I’ll add that to the docs. Thanks!

**Comment by aaliddell** [comment]
Added in #84
