### ISSUE TITLE
Maven central should all use https (not http)

### ISSUE THREAD

**Issue by humphrej** [rules-proto-grpc/rules_proto_grpc#50]
Since Jan 15, Maven central is requiring HTTPS [1]. I think that repositories.bzl needs to be updated to reflect that.

[1] see https://support.sonatype.com/hc/en-us/articles/360041287334
[2] see https://github.com/rules-proto-grpc/rules_proto_grpc/blob/master/repositories.bzl#L191

From my build output:
``
ERROR: /builder/server-core/proto/BUILD:14:1: //server-core/proto:healthcheck_java_proto depends on @javax_annotation_javax_annotation_api//jar:jar in repository @javax_annotation_javax_annotation_api which failed to fetch. no such package '@javax_annotation_javax_annotation_api//jar': java.io.IOException: Error downloading [http://central.maven.org/maven2/javax/annotation/javax.annotation-api/1.2/javax.annotation-api-1.2.jar] to /workspace/.bazel/external/javax_annotation_javax_annotation_api/javax.annotation-api-1.2.jar: GET returned 501 HTTPS Required
``

**Comment by aaliddell** [comment]
Yep, looks like the CI build has been failing since this change. Looks like just switching out `http://` for `https://` is all that is needed
