### ISSUE TITLE
grpc-web commonjs_grpc_compile error generating protobuf JS

### ISSUE THREAD

**Issue by humphrej** [rules-proto-grpc/rules_proto_grpc#58]
Hello rules_proto_grpc friends,
I am trying to generate grpc-web/typescript bindings for a grpc service, but my setup is giving an error on commonjs_grpc_compile.  A minimal example is in a git repo https://github.com/humphrej/rules_proto_grpc_ts_example (Bazel 1.2.1, rules_proto_grpc 1.0.2).

My service definition is :
https://github.com/humphrej/rules_proto_grpc_ts_example/blob/master/proto/sysinternals.proto

Based on https://github.com/grpc/grpc-web#typescript-support, and generating the files manually (these work), I want to generate:
* SysinternalsServiceClientPb.ts : a service stub in typescript (from the typescript protoc generator)
* sysinternals_pb.d.ts : a typescript type descriptor of the protobuf payloads (from the typescript protoc generator)
* sysinternals_pb.js : a javascript file containing the protobuf payloads (from the commonjs protoc generator)

A script to generate the files manually is in the repo
https://github.com/humphrej/rules_proto_grpc_ts_example/blob/master/run_protoc.sh

My Bazel build file is :
https://github.com/humphrej/rules_proto_grpc_ts_example/blob/master/proto/BUILD

Rules java_grpc_library and ts_grpc_compile both work, but commonjs_grpc_compile gives the following error:

> $ bazel build //...
DEBUG: /private/var/tmp/_bazel_humphrej/30d1a6d490a744b5cd1a1d6be8d4786a/external/rules_proto_grpc/aspect.bzl:375:13: ProtoCompile: bazel-out/host/bin/external/com_google_protobuf/protoc --descriptor_set_in=bazel-out/darwin-fastbuild/bin/external/com_google_protobuf/empty_proto-descriptor-set.proto.bin --plugin=protoc-gen-commonjs_plugin=bazel-out/darwin-opt-exec-2B5CBBC6/bin/external/com_github_grpc_grpc_web/javascript/net/grpc/web/protoc-gen-grpc-web --commonjs_plugin_out=import_style=commonjs,mode=grpcweb:bazel-out/darwin-fastbuild/bin/external/com_google_protobuf/empty_proto/commonjs_grpc_compile_aspect_verb1 google/protobuf/empty.proto
DEBUG: /private/var/tmp/_bazel_humphrej/30d1a6d490a744b5cd1a1d6be8d4786a/external/rules_proto_grpc/aspect.bzl:375:13: ProtoCompile: bazel-out/host/bin/external/com_google_protobuf/protoc --descriptor_set_in=bazel-out/darwin-fastbuild/bin/external/com_google_protobuf/empty_proto-descriptor-set.proto.bin:bazel-out/darwin-fastbuild/bin/proto/sysinternals_proto-descriptor-set.proto.bin --plugin=protoc-gen-commonjs_plugin=bazel-out/darwin-opt-exec-2B5CBBC6/bin/external/com_github_grpc_grpc_web/javascript/net/grpc/web/protoc-gen-grpc-web --commonjs_plugin_out=import_style=commonjs,mode=grpcweb:bazel-out/darwin-fastbuild/bin/proto/sysinternals_proto/commonjs_grpc_compile_aspect_verb1 proto/sysinternals.proto
INFO: Analyzed 5 targets (0 packages loaded, 0 targets configured).
INFO: Found 5 targets...
ERROR: /private/var/tmp/_bazel_humphrej/30d1a6d490a744b5cd1a1d6be8d4786a/external/com_google_protobuf/BUILD:309:2: output 'external/com_google_protobuf/empty_proto/commonjs_grpc_compile_aspect_verb1/google/protobuf/empty_grpc_web_pb.js' was not created
ERROR: /private/var/tmp/_bazel_humphrej/30d1a6d490a744b5cd1a1d6be8d4786a/external/com_google_protobuf/BUILD:309:2: not all outputs were created or valid
INFO: Elapsed time: 0.311s, Critical Path: 0.12s
INFO: 2 processes: 2 darwin-sandbox.
FAILED: Build did NOT complete successfully

**Comment by bnczk** [comment]
The root cause for this is probably [here](https://github.com/rules-proto-grpc/rules_proto_grpc/blob/710004771530d5bc51f69d22f3fc561879ef7cdd/github.com/grpc/grpc-web/BUILD.bazel#L16). The commonjs_plugin tries to generate a file  empty_grpc_web_pb.js, but since there is no service in the corresponding proto, the file is not generated. Changing the `outputs` to `output_directory = True` fixes this issue.

**Comment by humphrej** [comment]
@bnczk thanks - I can confirm that `output_directory = True` stops the error.  Is that a bug in the rule?

Unfortunately, even without the error the rule did not do what I expected - namely generate sysinternals_pb.js.  AFAICS this is not generated by any of the rules ts_grpc_compile, commonjs_grpc_compile, or commonjs_dts_grpc_compile, as they are not using the --js_out option on protoc.

**Comment by bnczk** [comment]
I guess thats a bug, yes. you can use the `nodejs_proto_compile` for generating the proto files

**Comment by humphrej** [comment]
Thanks - nodejs_proto_compile got it working for me.

**Comment by aaliddell** [comment]
I believe this was fixed when we set output_directory for grpc-web? Please reopen if still broken :+1:
