### ISSUE TITLE
grpc-web rules should support text (as well as binary) format

### ISSUE THREAD

**Issue by humphrej** [rules-proto-grpc/rules_proto_grpc#59]
Based on [the grpc-web docs](https://github.com/grpc/grpc-web#wire-format-mode), server streaming over grpc-web is only supported by the text mode format.  Currently, the grpc-web rules always use the binary format (see [here](https://github.com/rules-proto-grpc/rules_proto_grpc/blob/master/github.com/grpc/grpc-web/BUILD.bazel)).

The grpc-web rules should include an option to request either the text format or the binary format.

     mode=grpcwebtext

or

     mode=grpcweb

**Comment by aaliddell** [comment]
This will be solved in 3.0.0 #106

```starlark
closure_grpc_compile(
    name = "greeter_grpc-web_grpc",
    protos = ["@rules_proto_grpc//example/proto:greeter_grpc"],
    options = {
        "*": ["mode=grpcwebtext"]
    }
)
```
