### ISSUE TITLE
Python Requirements don't work with Python 3.5.2 

### ISSUE THREAD

**Issue by Smokrow** [rules-proto-grpc/rules_proto_grpc#61]
When using the Python GRPC Rules inside the official Bazel Docker Container `l.gcr.io/google/bazel:2.2.0` the Pip Package cannot be resolved. 

`No matching distribution found for grpclib==0.3.1 (from -r /root/.cache/bazel/_bazel_root/8c069df52082beee3c95ca17836fb8e2/external/rules_proto_grpc/python/requirements.txt (line 2))
)
`

Maybe making the requirements for grpclib und grpcio less strict could work.

Thanks for the great rules so far. Have not hit any problems before :)

**Comment by aaliddell** [comment]
So grpclib is only supported in python 3.6+, hence pip not being able to find any packages for 3.5. Assuming you aren’t using the grpclib rules, you could copy the requirements.txt file locally to your repo and remove the dependency, as we don’t have a mechanism within the rules/Bazel to detect minor python versions.

**Comment by Smokrow** [comment]
Yep. Thats what I did.

Ah i just saw that grpclib only supports python3.6. I thought it would be possible to loosen the requirement, but in that case we cant do anything about it. 

Thanks for the help!
