### ISSUE TITLE
Trouble with python-generated proto code's relative imports

### ISSUE THREAD

**Issue by kilogram** [rules-proto-grpc/rules_proto_grpc#62]
Consider a project with a local repository `proto` containing exclusively protos, which uses of rules_proto_grpc to generate python code in the root of the workspace. The protos in `proto` (I really should have picked a better name) reference each other, and so the python modules will have to as well.

```
├── BUILD
├── foo.py
├── proto
│   ├── base
│   │   └── nested
│   │       ├── a.proto
│   │       ├── b.proto
│   │       └── BUILD
│   └── WORKSPACE
└── WORKSPACE
```

In this case, the generated a.py will import base.nested.b, and foo.py will have no problem importing a. However, if "base" is renamed to "google", and any python module that provides something under the google namespace (e.g. protobuf) is installed via pip or the local package manager, a.py will not be able to import b.py, and so foo will fail to run.

I have a repo with minimal code that replicates this failure at https://github.com/kilogram/python_bazel_proto_imports. `blaze run :bar` always works, but `blaze run :foo` will fail if protobuf is `pip install`ed.

My ultimate goal is to have a local copy of `googleapis/googleapis` with just the protobufs and some super simple BUILD files; those naturally are all rooted at google. There may be a better way to use googleapis in a python build; I'm very open to suggestions.

```
marvin » blaze run :foo
<snip>
['FooServicServicer', 'FooServicStub', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'add_FooServicServicer_to_server', 'google_dot_nested_dot_a__pb2', 'google_dot_nested_dot_b__pb2', 'grpc']
marvin » sudo pip install protobuf
[sudo] password for kilogram: 
Collecting protobuf
  Downloading protobuf-3.11.3-cp38-cp38-manylinux1_x86_64.whl (1.3 MB)
     |████████████████████████████████| 1.3 MB 2.1 MB/s 
Requirement already satisfied: six>=1.9 in /usr/lib/python3.8/site-packages (from protobuf) (1.14.0)
Requirement already satisfied: setuptools in /usr/lib/python3.8/site-packages (from protobuf) (46.1.3)
Installing collected packages: protobuf
Successfully installed protobuf-3.11.3
marvin » blaze run :foo
<snip>
Traceback (most recent call last):
  File "/u/kilogram/.cache/bazel/_bazel_kilogram/677353ecb5b959f94f6d68821d2a4580/execroot/python_bazel_proto_imports/bazel-out/k8-fastbuild/bin/foo.runfiles/python_bazel_proto_imports/foo.py", line 1, in <module>
    from python_bazel_proto_imports.google_a_py_grpc_pb.google.nested import a_pb2_grpc
  File "/u/kilogram/.cache/bazel/_bazel_kilogram/677353ecb5b959f94f6d68821d2a4580/execroot/python_bazel_proto_imports/bazel-out/k8-fastbuild/bin/foo.runfiles/python_bazel_proto_imports/google_a_py_grpc_pb/google/nested/a_pb2_grpc.py", line 4, in <module>
    from google.nested import a_pb2 as google_dot_nested_dot_a__pb2
ModuleNotFoundError: No module named 'google.nested'
```

**Comment by aaliddell** [comment]
If you set `legacy_create_init = False` on the py_binary, do you still see the issue? This is a common issue with python binaries and that flag will hopefully be flipped to false by default in a future Bazel release.

**Comment by kilogram** [comment]
I'm afraid not; somehow, with `legacy_create_init = False`, `:foo` fails even without any google package installed. I suspect that's because of namespace pollution, but there is no directory named google in my site-packages. `:bar` always succeeds.

```
marvin » sudo pacman -Rns python-protobuf
error: target not found: python-protobuf
marvin » sudo pip uninstall protobuf
WARNING: Skipping protobuf as it is not installed.
marvin » python -c 'import google'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'google'
marvin » PAGER= git diff BUILD
diff --git a/BUILD b/BUILD
index 3f28a92..2e6c1f0 100644
--- a/BUILD
+++ b/BUILD
@@ -15,6 +15,7 @@ py_binary(
     deps = [
         ":google_a_py_grpc",
     ],
+    legacy_create_init = False,
 )
 
 python_grpc_library(
@@ -30,4 +31,5 @@ py_binary(
     deps = [
         ":ok_a_py_grpc",
     ],
+    legacy_create_init = False,
 )
marvin » blaze run :foo
INFO: Analyzed target //:foo (1 packages loaded, 4 targets configured).
INFO: Found 1 target...
Target //:foo up-to-date:
  bazel-bin/foo
INFO: Elapsed time: 0.095s, Critical Path: 0.01s
INFO: 0 processes.
INFO: Build completed successfully, 3 total actions
INFO: Build completed successfully, 3 total actions
Traceback (most recent call last):
  File "/u/kilogram/.cache/bazel/_bazel_kilogram/677353ecb5b959f94f6d68821d2a4580/execroot/python_bazel_proto_imports/bazel-out/k8-fastbuild/bin/foo.runfiles/python_bazel_proto_imports/foo.py", line 1, in <module>
    from python_bazel_proto_imports.google_a_py_grpc_pb.google.nested import a_pb2_grpc
  File "/u/kilogram/.cache/bazel/_bazel_kilogram/677353ecb5b959f94f6d68821d2a4580/execroot/python_bazel_proto_imports/bazel-out/k8-fastbuild/bin/foo.runfiles/python_bazel_proto_imports/google_a_py_grpc_pb/google/nested/a_pb2_grpc.py", line 4, in <module>
    from google.nested import a_pb2 as google_dot_nested_dot_a__pb2
ModuleNotFoundError: No module named 'google.nested'
marvin » blaze run :bar
INFO: Analyzed target //:bar (0 packages loaded, 4 targets configured).
INFO: Found 1 target...
Target //:bar up-to-date:
  bazel-bin/bar
INFO: Elapsed time: 0.078s, Critical Path: 0.01s
INFO: 0 processes.
INFO: Build completed successfully, 3 total actions
INFO: Build completed successfully, 3 total actions
['FooServicServicer', 'FooServicStub', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'add_FooServicServicer_to_server', 'base_dot_nested_dot_a__pb2', 'base_dot_nested_dot_b__pb2', 'grpc']
```

**Comment by smamessier** [comment]
Any updates on this?

**Comment by JoshuaCrestone** [comment]
Not related to the specific bug, but to the goal of @kilogram, I have been using those protos by adding the following:

# WORKSPACE
git_repository(
    name = "com_google_googleapis",
    remote = "https://github.com/googleapis/googleapis.git",
    commit = "4bef0001ac7040431ea24b6187424fdec9c08b1b",
    shallow_since = "1588704700 -0700"
)
load(
  "@com_google_googleapis//:repository_rules.bzl",
  "switched_rules_by_language")
switched_rules_by_language(
    name = "com_google_googleapis_imports",
    python = True,
)

# BUILD
load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
  name = "apis_proto",
  srcs = ["apis.proto"],
  deps = [
    "@com_google_googleapis//google/type:datetime_proto",
    "@com_google_googleapis//google/type:money_proto",
  ]
)

**Comment by aaliddell** [comment]
Sorry for the long wait, I haven't had much time to put into these rules recently, given the weird world circumstances.

A few ideas:
- Nested workspaces are a bit of a wildcard in the Bazel world. If the workspaces are unnested, is the same issue present?
- `rules_python` has historically had issues with so-called namespace packages, meaning the first package found with a specific name would hide all others. However, I thought this had been resolved.
- Can you print the python version in your top level executable? It occurred to me that you aren't specifying `python_version = "PY3"` and may be ending up running Python 2 (which has very different package loading behaviour).

Hopefully I'll get a chance to try the above, but you may be able to get to it quicker than I.
