### ISSUE TITLE
Unable to run python_proto_library rule

### ISSUE THREAD

**Issue by JoshuaCrestone** [rules-proto-grpc/rules_proto_grpc#63]
I am trying to use the Python rules - specifically python_proto_library. I am getting the following error on Mac OS X Catalina 10.15.4 running bazel 3.0.0:

```
ERROR: /private/var/tmp/_bazel_joshuaharrison/29b3465cefdffc832f5dd334d22b0ea7/external/rules_proto_grpc/repositories.bzl:341:13: in http_archive rule //external:six: Found reference to a workspace rule in a context where a build rule was expected; probably a reference to a target in that external repository, properly specified as @reponame//path/to/package:target, should have been specified by the requesting rule.
ERROR: Analysis of target '//crestone/simulator/protos:apis_proto_py' failed; build aborted: Analysis of target '//external:six' failed
```

### WORKSPACE
http_archive(
    name = "rules_proto_grpc",
    urls = ["https://github.com/rules-proto-grpc/rules_proto_grpc/archive/1.0.2.tar.gz"],
    sha256 = "5f0f2fc0199810c65a2de148a52ba0aff14d631d4e8202f41aff6a9d590a471b",
    strip_prefix = "rules_proto_grpc-1.0.2",
)

load("@rules_proto_grpc//:repositories.bzl",
  "rules_proto_grpc_toolchains", "rules_proto_grpc_repos")
rules_proto_grpc_toolchains()
rules_proto_grpc_repos()
load(
  "@rules_proto_grpc//python:repositories.bzl",
  rules_proto_grpc_python_repos="python_repos")
rules_proto_grpc_python_repos()

### BUILD
load("@rules_proto//proto:defs.bzl", "proto_library")
load("@rules_proto_grpc//python:defs.bzl", "python_proto_library")

proto_library(
  name = "apis_proto",
  srcs = ["apis.proto"],
  deps = [
    ":instruments_proto",
    ":shared_proto",
    "@com_google_googleapis//google/type:datetime_proto",
    "@com_google_googleapis//google/type:money_proto",
  ]
)

python_proto_library(
  name = "apis_proto_py",
  deps = [":apis_proto"],
)

**Comment by aaliddell** [comment]
Do you have any other rules in your workspace? In particular, any that might be loading `six`?

The `six` dependency is pretty simple, but is frequently depended upon by other repos so can be problematic. The `python_proto_library` rule [is tested](https://buildkite.com/bazel/rules-proto-grpc-rules-proto-grpc/builds/394#5b493ee6-1bd8-4d8a-a290-69b825981b5f) on OSX and doesn't appear to give the same error.

**Comment by cwill747** [comment]
I am hitting the same thing, only after starting to play with this repo. As far as I can tell, it's because I used another version of com_google_protobuf elsewhere in my project, that didn't have this commit - https://github.com/protocolbuffers/protobuf/commit/a74c43bbd906a42b6bf70668c5d515c6f1d8d2cb

Because of that, it didn't have the fix that went into the six definition, and because this repo only declares com_google_protobuf if not already declared, it was broken. 

In my situation, upgrading my dependency on com_google_protobuf to something over `3.9.0`, which seems to have fixed the problem for me at least.

**Comment by merickson-onduo** [comment]
I had the same issue. I got it to go away by re-ordering my WORKSPACE file. Specifically, `com_google_protobuf` has to load before `rules_proto_grpc`. I'm using versions:

- `com_google_protobuf : 3.12.13`
- `rules_proto_grpc : 1.0.2`

That made this particular problem go away, but triggered something else downstream with some conflict of the version of six in use. I think that's happening in `com_github_ali5h_rules_pip`

I'm going to admit that I'm not an expert at any of this, so if anyone has some pointers, that would be great.

**Comment by merickson-onduo** [comment]
So, basically, if I do *NOT* load `com_google_protobuf` before `rules_proto_grpc` in WORKSPACE - when trying to call `python_proto_library` I get the error:

```
in http_archive rule //external:six: Found reference to a workspace rule in a context where a build rule was expected; probably a reference to a target in that external repository, properly specified as @reponame//path/to/package:target, should have been specified by the requesting rule.
```

Corresponding to the line in WORKSPACE where I do this:

```
load("@rules_proto_grpc//python:repositories.bzl", rules_proto_grpc_python_repos="python_repos")
```

If I *DO* load `com_google_protobuf` before `rules_proto_grpc`, the call to `python_proto_library` will succeed, but an empty `six` library will float around and mess up downstream builds.

**Comment by aaliddell** [comment]
It sounds like the resolution was conflicting protobuf repo versions? In which case, there's not a lot that can be amended in this repo. If that's not the case, please reopen. Thanks
