### ISSUE TITLE
Is it possible to use this project with built in protoc plugins?

### ISSUE THREAD

**Issue by Monnoroch** [rules-proto-grpc/rules_proto_grpc#64]
I would like to use standard `protoc --swift_out=...` instead of the custom plugin `@rules_proto_grpc//swift:swift_plugin` which is a separate Swift binary. Is that possible with these rules?

**Comment by aaliddell** [comment]
These rules use the built in generators where available, but swift does not appear to be built in to standard protobuf, unless this has changed recently? Therefore, the plugin is required to generate swift definitions.

**Comment by Monnoroch** [comment]
Sorry, this was a silly question, an existing setup confused me into believing that the plugin is built in.
