### ISSUE TITLE
Protobuf library version

### ISSUE THREAD

**Issue by Trisfald** [rules-proto-grpc/rules_proto_grpc#77]
Hello,
In the master branch the protobuf library version used is 3.11.0. Is there any way to configure the rules to use the newest 3.12.0 or must the change be done in this repository?

Thanks

**Comment by aaliddell** [comment]
If you manually load the protobuf repo at the desired version in your WORKSPACE prior to loading this repo, that will take priority over the version loaded here. However, if there were any substantial changes in protobuf project layout across versions you may get some issues with Bazel being unable to find targets.

**Comment by Trisfald** [comment]
I'm able to use protobuf 3.12.4 by following your advice. Thank you!
