### ISSUE TITLE
Bazel fails to compile Java GRPC dependency in Bazel 3.4.1

### ISSUE THREAD

**Issue by rickwebiii** [rules-proto-grpc/rules_proto_grpc#78]
If you call java_repos in your WORKSPACE and use a java_grpc_library rule with Bazel 3.4.1, your build fails because compiling the GRPC dependency encounters GuardedBy errorprone violations and the build fails. I repro'd this on Windows, but it should fail on every OS due to the nature of the error.

I first tried bumping the dependency to a released tag version, but ran into compile errors (even 1.25x).

I've filed an issue on GRPC's Github and have a pull request to cherry-pick a change with the violation suppressions into the 1.24x branch (the commit rules_proto use as a dependency). Not sure if they'll take this change, but if they do, you simply need to bump the commit hash.

A demo of the fix in action is [here](https://github.com/rickwebiii/rules_proto_grpc/tree/bazel3).

**Comment by patsheerin** [comment]
Can also change the level of error rule with the following in .bazelrc so still builds as temp work around
build --javacopt='-Xep:GuardedBy:WARN'

**Comment by aaliddell** [comment]
Fixed in next release by using a newer gRPC version: #84 
Thanks
