### ISSUE TITLE
Add Dart rules for protobuf and grpc

### ISSUE THREAD

**Issue by jquenel** [rules-proto-grpc/rules_proto_grpc#80]
I believe that it should be possible to add rules to generate the dart bindings for protobuf and grpc.

This [protoc plugin ](https://github.com/dart-lang/protobuf/tree/master/protoc_plugin)should be enough to work with.

I can volunteer for this work, but would appreciate support from experienced bazel rules authors :slightly_smiling_face:

**Comment by mark-dropbear** [comment]
@aaliddell I just wanted to check if this was something you were still considering at all? I saw it was removed from the 4.0.0 release but wasn't sure what was driving that at all. I'm currently on the look out for a Dart solution also and the only other info on the topic I could find was here: https://github.com/cbracken/rules_dart/issues/59 but I would love to get on the more mainstream path if possible using rules-proto-grpc if possible.

**Comment by aaliddell** [comment]
Yep it's still something I'd like to get in. It was dropped from 4.0.0 because that release had become a massive change and I wanted to get it out the door. Since adding Dart is not a breaking change, I can safely make it in a 4.x.0 release. I expect it won't be in 4.1.0 though, just to give you realistic expectations.

**Comment by mark-dropbear** [comment]
No problems at all! Just wanted to say thank you in the meantime :)

**Comment by SpencerC** [comment]
Hey @aaliddell,
Any updates on this?

**Comment by loeffel-io** [comment]
Also very interested 👍

**Comment by loeffel-io** [comment]
any updates here?

**Comment by loeffel-io** [comment]
We could really need this ♥️

**Comment by aaliddell** [comment]
As far as I can tell: the dart rules for Bazel seem to have been long abandoned and no suitable set has been proposed for the BCR

**Comment by loeffel-io** [comment]
we use this for now btw: https://github.com/cbracken/rules_dart/issues/59#issuecomment-2021342847
