### ISSUE TITLE
Update protoc-gen-go-grpc

### ISSUE THREAD

**Issue by ash2k** [rules-proto-grpc/rules_proto_grpc#85]
There is a new version of the plugin to generate gRPC code for the new Go protobuf implementation. Details are here https://github.com/grpc/grpc-go/releases/tag/cmd%2Fprotoc-gen-go-grpc%2Fv1.0.0

You probably know this, but I thought I just create an issue anyway to get a notification when the support for it is added. Thank you very much for this set of rules, it is very useful!

**Comment by aaliddell** [comment]
It was released just after I did the updates to the go rules dependencies and I hadn’t circled back around to it yet. This’ll go in the next wave of updates, since the old plugin remains working presently.
