### ISSUE TITLE
Problem with python_grpc_compile with py_library and py3_image

### ISSUE THREAD

**Issue by DiegoLelis** [rules-proto-grpc/rules_proto_grpc#87]
I'm trying to use python_grpc_compile as a dependency on py_library and py3_image, and I'm running on the problem: 
`does not have mandatory providers: 'py' or 'PyInfo'`

Here is my relevant WORKSPACE config:
```
http_archive(
    name = "rules_proto_grpc",
    urls = ["https://github.com/rules-proto-grpc/rules_proto_grpc/archive/2.0.0.tar.gz"],
    sha256 = "d771584bbff98698e7cb3cb31c132ee206a972569f4dc8b65acbdd934d156b33",
    strip_prefix = "rules_proto_grpc-2.0.0",
)

#
# Python GRPC Proto rules
#

load("@rules_proto_grpc//:repositories.bzl", "rules_proto_grpc_toolchains", "rules_proto_grpc_repos")
rules_proto_grpc_toolchains()
rules_proto_grpc_repos()

load("@rules_proto//proto:repositories.bzl", "rules_proto_dependencies", "rules_proto_toolchains")
rules_proto_dependencies()
rules_proto_toolchains()

# GRPC Python specific
load("@rules_proto_grpc//python:repositories.bzl", rules_proto_grpc_python_repos="python_repos")

rules_proto_grpc_python_repos()
```

relevant rules for BUILD file
```
load("@rules_proto//proto:defs.bzl", "proto_library")
load("@rules_proto_grpc//python:defs.bzl", "python_grpc_compile")

proto_library(
    name = "pingpongpb_proto",
    srcs = ["ping_pong_api.proto"],
    visibility = ["//visibility:public"],
)

python_grpc_compile(
    name = "pingpong_python_grpc",
    deps = [":pingpongpb_proto"],
    visibility = ["//visibility:public"],
)

py_library(
    name = "pingpong_python_grpc_lib",
    deps = [":pingpong_python_grpc"],
    visibility = ["//visibility:public"],
)
```

This works:
`bazel build //:pingpong_python_grpc`

This fails:
`bazel build //:pingpong_python_grpc_lib`

Here is the log:
```
ERROR: ...../BUILD.bazel:48:11: in deps attribute of py_library rule //:pingpong_python_grpc_lib: '//:pingpong_python_grpc' does not have mandatory providers: 'py' or 'PyInfo
```

Is there a way for me to add py or PyInfo?
Am I using this on my BUILD file correctly?

**Comment by aaliddell** [comment]
You need to use python_grpc_library rather than python_grpc_compile. The former produces a proper py_library target, whilst the latter just does the protoc compilation.

**Comment by DiegoLelis** [comment]
When trying to do this using python_grpc_library, I get the error: 
```
Use --sandbox_debug to see verbose messages from the sandbox
external/com_github_grpc_grpc/src/core/ext/filters/client_channel/backend_metric.cc:24:10: fatal error: upb/upb.hpp: No such file or directory
   24 | #include "upb/upb.hpp"
```

**Comment by aaliddell** [comment]
Do you have grpc_deps in your workspace? See here: https://github.com/rules-proto-grpc/rules_proto_grpc/blob/master/python/README.md#workspace-4

That brings in the dependencies for the gRPC repo, which I believe upb is one of.

**Comment by DiegoLelis** [comment]
I do, this is how it is organized on my workspace:

```
#
# GRPC Proto rules
#
load("@rules_proto_grpc//:repositories.bzl", "rules_proto_grpc_repos", "rules_proto_grpc_toolchains")

rules_proto_grpc_toolchains()
rules_proto_grpc_repos()

rules_proto_dependencies()
rules_proto_toolchains()

# GRPC Python specific
load("@rules_proto_grpc//python:repositories.bzl", rules_proto_grpc_python_repos="python_repos")
rules_proto_grpc_python_repos()

load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")
grpc_deps()

load("@upb//bazel:workspace_deps.bzl", "upb_deps")
upb_deps()

```

**Comment by aaliddell** [comment]
In theory that should work, although the `upb_deps` shouldn't be necessary for these rules, but you might need it elsewhere for your project. Perhaps something earlier in the `WORKSPACE` file is loading a conflicting version beforehand. Do you have a minimal failing example?

**Comment by DiegoLelis** [comment]
On my end, just importing upb was causing the failure, it didn't matter if I put before or after the rules_proto_grpc HTTP import.
As soon as I removed upb, it worked fine.

**Comment by aaliddell** [comment]
Ok, sounds like this is resolved then? If not, please reopen.

I took a look at the upb version you had specified: the missing `upb.hpp` file was added in a commit 3 days after the commit you had pinned. So if you need a specific version of upb you can use a more recent commit and it should work; otherwise just remove it as you have done and let `grpc_deps` pull in the upb version it wants.
